jdbc.default.driverClassName=org.mariadb.jdbc.Driver
jdbc.default.url=jdbc:mariadb://database/lportal?dontTrackOpenResources=true&characterEncoding=UTF-8&holdResultsOpenOverStatementClose=true&useFastDateParsing=false
jdbc.default.username=dxpcloud
company.default.name=Liferay AC
company.default.web.id=liferay.com
terms.of.use.required=false
passwords.default.policy.change.required=false
retry.jdbc.on.startup.delay=5
retry.jdbc.on.startup.max.retries=5
dl.store.antivirus.enabled=true

liferay.feature.flag.LPD-34594=true
liferay.feature.flag.LPS-164563=true