argocd_helm_chart_version="9.1.5"
argo_workflows_helm_chart_version="0.47.3"
crossplane_helm_chart_version="2.1.3"
envoy_gateway_helm_chart_version="1.6.3"
external_secrets_helm_chart_version="1.0.0"
infrastructure_helm_chart_version="0.4.4"
infrastructure_provider_helm_chart_version="0.3.4"
liferay_helm_chart_version="0.4.7"
