/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.type.virtual.order.service.base;

import com.liferay.commerce.product.type.virtual.order.model.CommerceVirtualOrderItemFileEntry;
import com.liferay.commerce.product.type.virtual.order.service.CommerceVirtualOrderItemFileEntryLocalService;
import com.liferay.commerce.product.type.virtual.order.service.persistence.CommerceVirtualOrderItemFileEntryPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the commerce virtual order item file entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.product.type.virtual.order.service.impl.CommerceVirtualOrderItemFileEntryLocalServiceImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see com.liferay.commerce.product.type.virtual.order.service.impl.CommerceVirtualOrderItemFileEntryLocalServiceImpl
 * @generated
 */
public abstract class CommerceVirtualOrderItemFileEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CommerceVirtualOrderItemFileEntryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceVirtualOrderItemFileEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.commerce.product.type.virtual.order.service.CommerceVirtualOrderItemFileEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the commerce virtual order item file entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceVirtualOrderItemFileEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceVirtualOrderItemFileEntry the commerce virtual order item file entry
	 * @return the commerce virtual order item file entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceVirtualOrderItemFileEntry
		addCommerceVirtualOrderItemFileEntry(
			CommerceVirtualOrderItemFileEntry
				commerceVirtualOrderItemFileEntry) {

		commerceVirtualOrderItemFileEntry.setNew(true);

		return commerceVirtualOrderItemFileEntryPersistence.update(
			commerceVirtualOrderItemFileEntry);
	}

	/**
	 * Creates a new commerce virtual order item file entry with the primary key. Does not add the commerce virtual order item file entry to the database.
	 *
	 * @param commerceVirtualOrderItemFileEntryId the primary key for the new commerce virtual order item file entry
	 * @return the new commerce virtual order item file entry
	 */
	@Override
	@Transactional(enabled = false)
	public CommerceVirtualOrderItemFileEntry
		createCommerceVirtualOrderItemFileEntry(
			long commerceVirtualOrderItemFileEntryId) {

		return commerceVirtualOrderItemFileEntryPersistence.create(
			commerceVirtualOrderItemFileEntryId);
	}

	/**
	 * Deletes the commerce virtual order item file entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceVirtualOrderItemFileEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceVirtualOrderItemFileEntryId the primary key of the commerce virtual order item file entry
	 * @return the commerce virtual order item file entry that was removed
	 * @throws PortalException if a commerce virtual order item file entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceVirtualOrderItemFileEntry
			deleteCommerceVirtualOrderItemFileEntry(
				long commerceVirtualOrderItemFileEntryId)
		throws PortalException {

		return commerceVirtualOrderItemFileEntryPersistence.remove(
			commerceVirtualOrderItemFileEntryId);
	}

	/**
	 * Deletes the commerce virtual order item file entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceVirtualOrderItemFileEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceVirtualOrderItemFileEntry the commerce virtual order item file entry
	 * @return the commerce virtual order item file entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceVirtualOrderItemFileEntry
		deleteCommerceVirtualOrderItemFileEntry(
			CommerceVirtualOrderItemFileEntry
				commerceVirtualOrderItemFileEntry) {

		return commerceVirtualOrderItemFileEntryPersistence.remove(
			commerceVirtualOrderItemFileEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return commerceVirtualOrderItemFileEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CommerceVirtualOrderItemFileEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return commerceVirtualOrderItemFileEntryPersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.type.virtual.order.model.impl.CommerceVirtualOrderItemFileEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return commerceVirtualOrderItemFileEntryPersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.type.virtual.order.model.impl.CommerceVirtualOrderItemFileEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return commerceVirtualOrderItemFileEntryPersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return commerceVirtualOrderItemFileEntryPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return commerceVirtualOrderItemFileEntryPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public CommerceVirtualOrderItemFileEntry
		fetchCommerceVirtualOrderItemFileEntry(
			long commerceVirtualOrderItemFileEntryId) {

		return commerceVirtualOrderItemFileEntryPersistence.fetchByPrimaryKey(
			commerceVirtualOrderItemFileEntryId);
	}

	/**
	 * Returns the commerce virtual order item file entry matching the UUID and group.
	 *
	 * @param uuid the commerce virtual order item file entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching commerce virtual order item file entry, or <code>null</code> if a matching commerce virtual order item file entry could not be found
	 */
	@Override
	public CommerceVirtualOrderItemFileEntry
		fetchCommerceVirtualOrderItemFileEntryByUuidAndGroupId(
			String uuid, long groupId) {

		return commerceVirtualOrderItemFileEntryPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the commerce virtual order item file entry with the primary key.
	 *
	 * @param commerceVirtualOrderItemFileEntryId the primary key of the commerce virtual order item file entry
	 * @return the commerce virtual order item file entry
	 * @throws PortalException if a commerce virtual order item file entry with the primary key could not be found
	 */
	@Override
	public CommerceVirtualOrderItemFileEntry
			getCommerceVirtualOrderItemFileEntry(
				long commerceVirtualOrderItemFileEntryId)
		throws PortalException {

		return commerceVirtualOrderItemFileEntryPersistence.findByPrimaryKey(
			commerceVirtualOrderItemFileEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			commerceVirtualOrderItemFileEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			CommerceVirtualOrderItemFileEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceVirtualOrderItemFileEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			commerceVirtualOrderItemFileEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CommerceVirtualOrderItemFileEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceVirtualOrderItemFileEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			commerceVirtualOrderItemFileEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			CommerceVirtualOrderItemFileEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceVirtualOrderItemFileEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<CommerceVirtualOrderItemFileEntry>() {

				@Override
				public void performAction(
						CommerceVirtualOrderItemFileEntry
							commerceVirtualOrderItemFileEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, commerceVirtualOrderItemFileEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					CommerceVirtualOrderItemFileEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceVirtualOrderItemFileEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CommerceVirtualOrderItemFileEntryLocalServiceImpl#deleteCommerceVirtualOrderItemFileEntry(CommerceVirtualOrderItemFileEntry) to avoid orphaned data");
		}

		return commerceVirtualOrderItemFileEntryLocalService.
			deleteCommerceVirtualOrderItemFileEntry(
				(CommerceVirtualOrderItemFileEntry)persistedModel);
	}

	@Override
	public BasePersistence<CommerceVirtualOrderItemFileEntry>
		getBasePersistence() {

		return commerceVirtualOrderItemFileEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceVirtualOrderItemFileEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the commerce virtual order item file entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the commerce virtual order item file entries
	 * @param companyId the primary key of the company
	 * @return the matching commerce virtual order item file entries, or an empty list if no matches were found
	 */
	@Override
	public List<CommerceVirtualOrderItemFileEntry>
		getCommerceVirtualOrderItemFileEntriesByUuidAndCompanyId(
			String uuid, long companyId) {

		return commerceVirtualOrderItemFileEntryPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of commerce virtual order item file entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the commerce virtual order item file entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of commerce virtual order item file entries
	 * @param end the upper bound of the range of commerce virtual order item file entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching commerce virtual order item file entries, or an empty list if no matches were found
	 */
	@Override
	public List<CommerceVirtualOrderItemFileEntry>
		getCommerceVirtualOrderItemFileEntriesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<CommerceVirtualOrderItemFileEntry>
				orderByComparator) {

		return commerceVirtualOrderItemFileEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the commerce virtual order item file entry matching the UUID and group.
	 *
	 * @param uuid the commerce virtual order item file entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching commerce virtual order item file entry
	 * @throws PortalException if a matching commerce virtual order item file entry could not be found
	 */
	@Override
	public CommerceVirtualOrderItemFileEntry
			getCommerceVirtualOrderItemFileEntryByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return commerceVirtualOrderItemFileEntryPersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the commerce virtual order item file entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.type.virtual.order.model.impl.CommerceVirtualOrderItemFileEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of commerce virtual order item file entries
	 * @param end the upper bound of the range of commerce virtual order item file entries (not inclusive)
	 * @return the range of commerce virtual order item file entries
	 */
	@Override
	public List<CommerceVirtualOrderItemFileEntry>
		getCommerceVirtualOrderItemFileEntries(int start, int end) {

		return commerceVirtualOrderItemFileEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of commerce virtual order item file entries.
	 *
	 * @return the number of commerce virtual order item file entries
	 */
	@Override
	public int getCommerceVirtualOrderItemFileEntriesCount() {
		return commerceVirtualOrderItemFileEntryPersistence.countAll();
	}

	/**
	 * Updates the commerce virtual order item file entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceVirtualOrderItemFileEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceVirtualOrderItemFileEntry the commerce virtual order item file entry
	 * @return the commerce virtual order item file entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceVirtualOrderItemFileEntry
		updateCommerceVirtualOrderItemFileEntry(
			CommerceVirtualOrderItemFileEntry
				commerceVirtualOrderItemFileEntry) {

		return commerceVirtualOrderItemFileEntryPersistence.update(
			commerceVirtualOrderItemFileEntry);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CommerceVirtualOrderItemFileEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		commerceVirtualOrderItemFileEntryLocalService =
			(CommerceVirtualOrderItemFileEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceVirtualOrderItemFileEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceVirtualOrderItemFileEntry.class;
	}

	protected String getModelClassName() {
		return CommerceVirtualOrderItemFileEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			commerceVirtualOrderItemFileEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CommerceVirtualOrderItemFileEntryLocalService
		commerceVirtualOrderItemFileEntryLocalService;

	@Reference
	protected CommerceVirtualOrderItemFileEntryPersistence
		commerceVirtualOrderItemFileEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CommerceVirtualOrderItemFileEntryLocalServiceBaseImpl.class);

}
// SB-Hash:-814645557