modified.files.includes[relevant][site-navigation-site-map-web-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql84][relevant][site-navigation-site-map-web-rule]=\
    site-navigation-site-map-web.main

relevant.rule.names=site-navigation-site-map-web-rule

test.batch.names[relevant][site-navigation-site-map-web-rule]=\
    playwright-js-tomcat101-mysql84

testray.main.component.name=Site Map Widget