##
## Test Suites
##

    modified.files.includes[relevant][batch-engine-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=batch-engine-java-rule

    test.batch.names[relevant][batch-engine-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][batch-engine-java-rule]=\
        apps/batch-engine/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][batch-engine-java-rule]=\
        apps/batch-engine/**/*Test.java

##
## Testray
##

    testray.main.component.name=Headless Batch Engine API