##
## Test Suites
##

    modified.files.includes[relevant][dispatch-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    modified.files.includes[relevant][dispatch-playwright-rule]=**

    relevant.rule.names=\
        dispatch-java-rule,\
        dispatch-playwright-rule

    test.batch.names[relevant][dispatch-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    test.batch.names[relevant][dispatch-playwright-rule]=\
        playwright-js-tomcat90-postgresql155

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][dispatch-java-rule]=\
        apps/dispatch/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][dispatch-java-rule]=\
        apps/dispatch/**/*Test.java

    playwright.projects.includes[playwright-js-tomcat90-postgresql155][relevant][dispatch-playwright-rule]=\
        dispatch-web

    test.batch.class.names.includes[relevant][dispatch-rule]=\
        **/dispatch/**/*Test.java

##
## Testray
##

    testray.main.component.name=Job Scheduler