{{- if .Values.createClusterResources -}}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
    labels:
        {{- include "liferayAWSBackupRestore.labels" . | nindent 8 }}
    name: {{ include "liferayAWSBackupRestore.name" . }}
spec:
    arguments:
        parameters:
            -   name: recovery-point-arn
    artifactGC:
        {{- .Values.argo.workflowSpec.artifactGC | toYaml | nindent 8 }}
    artifactRepositoryRef:
        configMap: {{ include "liferayAWSBackupRestore.artifactRepositoryConfigMapName" . }}
    entrypoint: main
    podGC:
        {{- .Values.argo.workflowSpec.podGC | toYaml | nindent 8 }}
    templates:
        -   inputs:
                parameters:
                    -   name: restore-phase
                    -   default: "null"
                        name: snapshot-identifier
                    -   name: target-active-data-plane
            name: apply-infrastructure
            outputs:
                parameters:
                    -   name: generation
                        valueFrom:
                            jsonPath: "{.metadata.generation}"
            resource:
                action: patch
                manifest: |-
                    apiVersion: aws.liferay.com/v1alpha1
                    kind: LiferayInfrastructure
                    metadata:
                        name: {{ include "liferayAWSBackupRestore.liferayInfrastructureName" . }}
                        namespace: {{ .Release.Namespace }}
                    spec:
                        database:
                            snapshotIdentifier: {{ "{{" }}inputs.parameters.snapshot-identifier}}
                        restorePhase: {{ "{{" }}inputs.parameters.restore-phase}}
                        targetActiveDataPlane: {{ "{{" }}inputs.parameters.target-active-data-plane}}
                mergeStrategy: merge
        -   inputs:
                parameters:
                    -   name: restore-phase
                    -   default: "null"
                        name: snapshot-identifier
                    -   name: target-active-data-plane
            name: apply-wait-infrastructure
            steps:
                -   -   arguments:
                            parameters:
                                -   name: restore-phase
                                    value: "{{ "{{" }}inputs.parameters.restore-phase}}"
                                -   name: snapshot-identifier
                                    value: "{{ "{{" }}inputs.parameters.snapshot-identifier}}"
                                -   name: target-active-data-plane
                                    value: "{{ "{{" }}inputs.parameters.target-active-data-plane}}"
                        name: apply-infrastructure
                        template: apply-infrastructure
                -   -   arguments:
                            parameters:
                                -   name: expected-generation
                                    value: "{{ "{{" }}steps.apply-infrastructure.outputs.parameters.generation}}"
                        name: wait-infrastructure-ready
                        template: wait-infrastructure-ready
        -   container:
                args:
                    -   "s3"
                    -   "rm"
                    -   "s3://{{ "{{" }}inputs.parameters.s3-bucket-id}}/"
                    -   "--only-show-errors"
                    -   "--recursive"
                command: ["aws"]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            inputs:
                parameters:
                    -   name: s3-bucket-id
            name: clean-up-s3-bucket
        -   name: get-current-infrastructure-state
            outputs:
                parameters:
                    -   name: data-active
                        valueFrom:
                            path: /tmp/data-active.txt
                    -   name: data-inactive
                        valueFrom:
                            path: /tmp/data-inactive.txt
                    -   name: s3-bucket-id-active
                        valueFrom:
                            path: /tmp/s3-bucket-id-active.txt
                    -   name: s3-bucket-id-inactive
                        valueFrom:
                            path: /tmp/s3-bucket-id-inactive.txt
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.getCurrentInfrastructureState" . | nindent 20 }}
        -   name: get-peer-recovery-points
            outputs:
                parameters:
                    -   name: rds-snapshot-id
                        valueFrom:
                            path: /tmp/rds-snapshot-id.txt
                    -   name: s3-recovery-point-arn
                        valueFrom:
                            path: /tmp/s3-recovery-point-arn.txt
            script:
                command: [sh]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.getPeerRecoveryPoints" . | nindent 20 }}
        -   container:
                args:
                    -   rollout
                    -   restart
                    -   statefulset
                    -   "{{ .Values.liferayWorkload.name }}"
                command: [kubectl]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: kubectl-rollout-restart
        -   container:
                args:
                    -   rollout
                    -   status
                    -   statefulset
                    -   "{{ .Values.liferayWorkload.name }}"
                    -   --timeout={{ .Values.liferayWorkload.rolloutTimeout }}
                command: [kubectl]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
            name: kubectl-rollout-status
        -   dag:
                tasks:
                    -   arguments:
                            parameters:
                                -   name: restore-phase
                                    value: none
                                -   name: target-active-data-plane
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-inactive}}"
                        depends: restart-liferay
                        name: clean-up-rds-instance
                        template: apply-wait-infrastructure
                    -   arguments:
                            parameters:
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-active}}"
                        depends: restart-liferay
                        name: clean-up-s3-bucket
                        template: clean-up-s3-bucket
                    -   name: get-current-infrastructure-state
                        template: get-current-infrastructure-state
                    -   name: get-peer-recovery-points
                        template: get-peer-recovery-points
                    -   arguments:
                            parameters:
                                -   name: restore-phase
                                    value: promoting
                                -   name: target-active-data-plane
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-inactive}}"
                        depends: restore-rds-instance && restore-s3-bucket
                        name: promote-inactive-data-plane
                        template: apply-wait-infrastructure
                    -   depends: promote-inactive-data-plane
                        name: restart-liferay
                        template: restart-liferay
                    -   arguments:
                            parameters:
                                -   name: restore-phase
                                    value: provisioning
                                -   name: snapshot-identifier
                                    value: "{{ "{{" }}tasks.get-peer-recovery-points.outputs.parameters.rds-snapshot-id}}"
                                -   name: target-active-data-plane
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-inactive}}"
                        depends: get-current-infrastructure-state && get-peer-recovery-points
                        name: restore-rds-instance
                        template: apply-wait-infrastructure
                    -   arguments:
                            parameters:
                                -   name: s3-recovery-point-arn
                                    value: "{{ "{{" }}tasks.get-peer-recovery-points.outputs.parameters.s3-recovery-point-arn}}"
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-inactive}}"
                        depends: get-current-infrastructure-state && get-peer-recovery-points
                        name: restore-s3-bucket
                        template: restore-s3-bucket
                    -   arguments:
                            parameters:
                                -   name: restore-phase
                                    value: none
                                -   name: target-active-data-plane
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.data-active}}"
                        depends: "!restore-rds-instance.Omitted && !restore-rds-instance.Skipped && !promote-inactive-data-plane.Succeeded"
                        name: roll-back-rds-instance
                        template: apply-wait-infrastructure
                    -   arguments:
                            parameters:
                                -   name: s3-bucket-id
                                    value: "{{ "{{" }}tasks.get-current-infrastructure-state.outputs.parameters.s3-bucket-id-inactive}}"
                        depends: "!restore-s3-bucket.Omitted && !restore-s3-bucket.Skipped && !promote-inactive-data-plane.Succeeded"
                        name: roll-back-s3-bucket
                        template: clean-up-s3-bucket
            name: main
        -   inputs:
                parameters:
                    -   name: s3-bucket-id
                    -   name: s3-recovery-point-arn
            name: restore-s3-bucket
            script:
                command: [sh]
                image: "{{ .Values.images.awsCli.repository }}:{{ .Values.images.awsCli.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.restoreS3Bucket" . | nindent 20 }}
        -   name: restart-liferay
            steps:
                -   -   name: kubectl-rollout-restart
                        template: kubectl-rollout-restart
                -   -   name: kubectl-rollout-status
                        template: kubectl-rollout-status
        -   inputs:
                parameters:
                    -   name: expected-generation
            name: wait-infrastructure-ready
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- include "liferayAWSBackupRestore.script.waitInfrastructureReady" . | nindent 20 }}
    ttlStrategy:
        {{- .Values.argo.workflowSpec.ttlStrategy | toYaml | nindent 8 }}
{{- end -}}