{{- $defaultArtifactRepository := "artifact-repository" -}}
apiVersion: v1
data:
    {{ $defaultArtifactRepository }}: |-
        s3:
            bucket: {{ printf "%s-argo-wf" (include "liferayAWSBackupRestore.infraResourceBaseName" .) }}
            endpoint: s3.amazonaws.com
kind: ConfigMap
metadata:
    annotations:
        workflows.argoproj.io/default-artifact-repository: {{ $defaultArtifactRepository }}
    name: {{ include "liferayAWSBackupRestore.artifactRepositoryConfigMapName" . }}