apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
    annotations:
        eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%v:role/%s-backup-restore-role" .Values.global.aws.accountId (include "liferayAWSBackupRestore.infraResourceBaseName" .) | quote }}
    labels:
    {{- include "liferayAWSBackupRestore.labels" . | nindent 8 }}
    name: backup-restore