argo:
    workflowSpec:
        artifactGC:
            strategy: OnWorkflowDeletion
        podGC:
            strategy: OnWorkflowSuccess
        ttlStrategy:
            secondsAfterCompletion: 86400
awsBackupService:
    restoreWaitTimeoutSeconds: 7200
createClusterResources: true
fullnameOverride: ""
images:
    awsCli:
        repository: amazon/aws-cli
        tag: 2.27.63
    helmKubectl:
        repository: dtzar/helm-kubectl
        tag: 4.1.1
liferayInfrastructure:
    name: ""
    waitTimeoutSeconds: 3600
liferayWorkload:
    name: liferay-default
    rolloutTimeout: 15m
nameOverride: ""
resources:
    default:
        limits:
            cpu: 250m
            memory: 256Mi
        requests:
            cpu: 100m
            memory: 128Mi