##
## Test Suites
##

    modified.files.includes[relevant][asset-entry-rel-service-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=asset-entry-rel-service-java-rule

    test.batch.names[relevant][asset-entry-rel-service-java-rule]=\
<<<<<<< HEAD
        modules-integration-postgresql155,\
=======
<<<<<<< HEAD
        modules-integration-mysql57,\
=======
        modules-integration-postgresql163,\
>>>>>>> 8963b385431f4 (LPD-50277 Update to postgresql163)
>>>>>>> ca7154f2c958e (LPD-50277 Update to postgresql163)
        modules-unit

    #
    # Relevant
    #

<<<<<<< HEAD
    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155][relevant][asset-entry-rel-service-java-rule]=\
=======
<<<<<<< HEAD
    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][asset-entry-rel-service-java-rule]=\
=======
    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-entry-rel-service-java-rule]=\
>>>>>>> 8963b385431f4 (LPD-50277 Update to postgresql163)
>>>>>>> ca7154f2c958e (LPD-50277 Update to postgresql163)
        **/asset-entry-rel-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-entry-rel-service-java-rule]=\
        **/asset-entry-rel-test/**/*Test.java