backup:
    enabled: false
    rules:
        -   retentionDays: 30
            ruleName: daily-backups
            schedule: cron(0 5 * * ? *)
            startWindow: 60
database:
    engine: postgres
    engineVersion: "16.11"
    instanceClass: db.t3.medium
    storageGB: 20
    username: liferay_database_admin
deletionProtection: false
enabled: true
endpoints: {}
gateway: {}
license: {}
overlay: {}
search:
    opensearch:
        engineVersion: OpenSearch_2.15
        instanceCount: 1
        instanceType: t3.small.search
        username: liferay_search_admin
storage: {}