/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CommerceChannelAccountEntryRel;
import com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceChannelAccountEntryRel service. Represents a row in the &quot;CChannelAccountEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceChannelAccountEntryRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceChannelAccountEntryRelImpl
 * @see CommerceChannelAccountEntryRel
 * @generated
 */
public abstract class CommerceChannelAccountEntryRelBaseImpl
	extends CommerceChannelAccountEntryRelModelImpl
	implements CommerceChannelAccountEntryRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce channel account entry rel model instance should use the <code>CommerceChannelAccountEntryRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceChannelAccountEntryRelLocalServiceUtil.
				addCommerceChannelAccountEntryRel(this);
		}
		else {
			CommerceChannelAccountEntryRelLocalServiceUtil.
				updateCommerceChannelAccountEntryRel(this);
		}
	}

}
// SB-Hash:-176755623