/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPConfigurationEntrySetting;
import com.liferay.commerce.product.service.CPConfigurationEntrySettingLocalServiceUtil;

/**
 * The extended model base implementation for the CPConfigurationEntrySetting service. Represents a row in the &quot;CPConfigurationEntrySetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPConfigurationEntrySettingImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPConfigurationEntrySettingImpl
 * @see CPConfigurationEntrySetting
 * @generated
 */
public abstract class CPConfigurationEntrySettingBaseImpl
	extends CPConfigurationEntrySettingModelImpl
	implements CPConfigurationEntrySetting {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp configuration entry setting model instance should use the <code>CPConfigurationEntrySetting</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPConfigurationEntrySettingLocalServiceUtil.
				addCPConfigurationEntrySetting(this);
		}
		else {
			CPConfigurationEntrySettingLocalServiceUtil.
				updateCPConfigurationEntrySetting(this);
		}
	}

}
// SB-Hash:-819891093