/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPConfigurationListRel;
import com.liferay.commerce.product.service.CPConfigurationListRelLocalServiceUtil;

/**
 * The extended model base implementation for the CPConfigurationListRel service. Represents a row in the &quot;CPConfigurationListRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPConfigurationListRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPConfigurationListRelImpl
 * @see CPConfigurationListRel
 * @generated
 */
public abstract class CPConfigurationListRelBaseImpl
	extends CPConfigurationListRelModelImpl implements CPConfigurationListRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp configuration list rel model instance should use the <code>CPConfigurationListRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPConfigurationListRelLocalServiceUtil.addCPConfigurationListRel(
				this);
		}
		else {
			CPConfigurationListRelLocalServiceUtil.updateCPConfigurationListRel(
				this);
		}
	}

}
// SB-Hash:1329900611