/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPOptionCategory;
import com.liferay.commerce.product.service.CPOptionCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the CPOptionCategory service. Represents a row in the &quot;CPOptionCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPOptionCategoryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPOptionCategoryImpl
 * @see CPOptionCategory
 * @generated
 */
public abstract class CPOptionCategoryBaseImpl
	extends CPOptionCategoryModelImpl implements CPOptionCategory {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp option category model instance should use the <code>CPOptionCategory</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPOptionCategoryLocalServiceUtil.addCPOptionCategory(this);
		}
		else {
			CPOptionCategoryLocalServiceUtil.updateCPOptionCategory(this);
		}
	}

}
// SB-Hash:-875653943