/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPOptionValue;
import com.liferay.commerce.product.service.CPOptionValueLocalServiceUtil;

/**
 * The extended model base implementation for the CPOptionValue service. Represents a row in the &quot;CPOptionValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPOptionValueImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPOptionValueImpl
 * @see CPOptionValue
 * @generated
 */
public abstract class CPOptionValueBaseImpl
	extends CPOptionValueModelImpl implements CPOptionValue {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp option value model instance should use the <code>CPOptionValue</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPOptionValueLocalServiceUtil.addCPOptionValue(this);
		}
		else {
			CPOptionValueLocalServiceUtil.updateCPOptionValue(this);
		}
	}

}
// SB-Hash:1591759057