##
## Test Suites
##

    modified.files.includes[relevant][css-builder-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=css-builder-java-rule

    test.batch.names[relevant][css-builder-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][css-builder-java-rule]=\
        util/css-builder/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][css-builder-java-rule]=\
        util/css-builder/**/*Test.java

##
## Testray
##

    testray.main.component.name=Dev Tools