{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-db-root-password" .Release.Name)) }}
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
        helm.sh/resource-policy: keep
    name: {{ .Release.Name }}-db-root-password
    namespace: {{ .Release.Namespace }}
stringData:
    password: {{ randAlphaNum 16 | quote }}
type: Opaque
{{- end }}