/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.model.CountryLocalization;

/**
 * The extended model base implementation for the CountryLocalization service. Represents a row in the &quot;CountryLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CountryLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CountryLocalizationImpl
 * @see CountryLocalization
 * @generated
 */
public abstract class CountryLocalizationBaseImpl
	extends CountryLocalizationModelImpl implements CountryLocalization {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a country localization model instance should use the <code>CountryLocalization</code> interface instead.
	 */

}