##
## Test Suites
##

    modified.files.includes[relevant][batch-planner-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    modified.files.includes[relevant][batch-planner-playwright-rule]=**

    relevant.rule.names=\
        batch-planner-java-rule,\
        batch-planner-playwright-rule

    test.batch.names[relevant][batch-planner-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    test.batch.names[relevant][batch-planner-playwright-rule]=\
        playwright-js-tomcat90-postgresql155

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][batch-planner-java-rule]=\
        apps/batch-planner/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][batch-planner-java-rule]=\
        apps/batch-planner/**/*Test.java

    playwright.projects.includes[playwright-js-tomcat90-postgresql155][relevant][batch-planner-playwright-rule]=\
        batch-planner

    test.batch.class.names.includes[relevant][batch-planner-rule]=\
        **/batch-planner/**/*Test.java

##
## Testray
##

    testray.main.component.name=Data Migration Center