/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.segments.model.impl;

import com.liferay.segments.model.SegmentsEntry;
import com.liferay.segments.service.SegmentsEntryLocalServiceUtil;

/**
 * The extended model base implementation for the SegmentsEntry service. Represents a row in the &quot;SegmentsEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SegmentsEntryImpl}.
 * </p>
 *
 * @author Eduardo Garcia
 * @see SegmentsEntryImpl
 * @see SegmentsEntry
 * @generated
 */
public abstract class SegmentsEntryBaseImpl
	extends SegmentsEntryModelImpl implements SegmentsEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a segments entry model instance should use the <code>SegmentsEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SegmentsEntryLocalServiceUtil.addSegmentsEntry(this);
		}
		else {
			SegmentsEntryLocalServiceUtil.updateSegmentsEntry(this);
		}
	}

}
// SB-Hash:-243625830