/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.service.base;

import com.liferay.commerce.product.model.CPConfigurationEntrySetting;
import com.liferay.commerce.product.service.CPConfigurationEntrySettingLocalService;
import com.liferay.commerce.product.service.persistence.CPConfigurationEntrySettingPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cp configuration entry setting local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.product.service.impl.CPConfigurationEntrySettingLocalServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.product.service.impl.CPConfigurationEntrySettingLocalServiceImpl
 * @generated
 */
public abstract class CPConfigurationEntrySettingLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CPConfigurationEntrySettingLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CPConfigurationEntrySettingLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.commerce.product.service.CPConfigurationEntrySettingLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cp configuration entry setting to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPConfigurationEntrySettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpConfigurationEntrySetting the cp configuration entry setting
	 * @return the cp configuration entry setting that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPConfigurationEntrySetting addCPConfigurationEntrySetting(
		CPConfigurationEntrySetting cpConfigurationEntrySetting) {

		cpConfigurationEntrySetting.setNew(true);

		return cpConfigurationEntrySettingPersistence.update(
			cpConfigurationEntrySetting);
	}

	/**
	 * Creates a new cp configuration entry setting with the primary key. Does not add the cp configuration entry setting to the database.
	 *
	 * @param CPConfigurationEntrySettingId the primary key for the new cp configuration entry setting
	 * @return the new cp configuration entry setting
	 */
	@Override
	@Transactional(enabled = false)
	public CPConfigurationEntrySetting createCPConfigurationEntrySetting(
		long CPConfigurationEntrySettingId) {

		return cpConfigurationEntrySettingPersistence.create(
			CPConfigurationEntrySettingId);
	}

	/**
	 * Deletes the cp configuration entry setting with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPConfigurationEntrySettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param CPConfigurationEntrySettingId the primary key of the cp configuration entry setting
	 * @return the cp configuration entry setting that was removed
	 * @throws PortalException if a cp configuration entry setting with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPConfigurationEntrySetting deleteCPConfigurationEntrySetting(
			long CPConfigurationEntrySettingId)
		throws PortalException {

		return cpConfigurationEntrySettingPersistence.remove(
			CPConfigurationEntrySettingId);
	}

	/**
	 * Deletes the cp configuration entry setting from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPConfigurationEntrySettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpConfigurationEntrySetting the cp configuration entry setting
	 * @return the cp configuration entry setting that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPConfigurationEntrySetting deleteCPConfigurationEntrySetting(
		CPConfigurationEntrySetting cpConfigurationEntrySetting) {

		return cpConfigurationEntrySettingPersistence.remove(
			cpConfigurationEntrySetting);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return cpConfigurationEntrySettingPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CPConfigurationEntrySetting.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cpConfigurationEntrySettingPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPConfigurationEntrySettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cpConfigurationEntrySettingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPConfigurationEntrySettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cpConfigurationEntrySettingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cpConfigurationEntrySettingPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cpConfigurationEntrySettingPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CPConfigurationEntrySetting fetchCPConfigurationEntrySetting(
		long CPConfigurationEntrySettingId) {

		return cpConfigurationEntrySettingPersistence.fetchByPrimaryKey(
			CPConfigurationEntrySettingId);
	}

	/**
	 * Returns the cp configuration entry setting matching the UUID and group.
	 *
	 * @param uuid the cp configuration entry setting's UUID
	 * @param groupId the primary key of the group
	 * @return the matching cp configuration entry setting, or <code>null</code> if a matching cp configuration entry setting could not be found
	 */
	@Override
	public CPConfigurationEntrySetting
		fetchCPConfigurationEntrySettingByUuidAndGroupId(
			String uuid, long groupId) {

		return cpConfigurationEntrySettingPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the cp configuration entry setting with the primary key.
	 *
	 * @param CPConfigurationEntrySettingId the primary key of the cp configuration entry setting
	 * @return the cp configuration entry setting
	 * @throws PortalException if a cp configuration entry setting with the primary key could not be found
	 */
	@Override
	public CPConfigurationEntrySetting getCPConfigurationEntrySetting(
			long CPConfigurationEntrySettingId)
		throws PortalException {

		return cpConfigurationEntrySettingPersistence.findByPrimaryKey(
			CPConfigurationEntrySettingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			cpConfigurationEntrySettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CPConfigurationEntrySetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPConfigurationEntrySettingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cpConfigurationEntrySettingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CPConfigurationEntrySetting.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPConfigurationEntrySettingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			cpConfigurationEntrySettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CPConfigurationEntrySetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPConfigurationEntrySettingId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<CPConfigurationEntrySetting>() {

				@Override
				public void performAction(
						CPConfigurationEntrySetting cpConfigurationEntrySetting)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, cpConfigurationEntrySetting);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					CPConfigurationEntrySetting.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpConfigurationEntrySettingPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CPConfigurationEntrySettingLocalServiceImpl#deleteCPConfigurationEntrySetting(CPConfigurationEntrySetting) to avoid orphaned data");
		}

		return cpConfigurationEntrySettingLocalService.
			deleteCPConfigurationEntrySetting(
				(CPConfigurationEntrySetting)persistedModel);
	}

	@Override
	public BasePersistence<CPConfigurationEntrySetting> getBasePersistence() {
		return cpConfigurationEntrySettingPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpConfigurationEntrySettingPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the cp configuration entry settings matching the UUID and company.
	 *
	 * @param uuid the UUID of the cp configuration entry settings
	 * @param companyId the primary key of the company
	 * @return the matching cp configuration entry settings, or an empty list if no matches were found
	 */
	@Override
	public List<CPConfigurationEntrySetting>
		getCPConfigurationEntrySettingsByUuidAndCompanyId(
			String uuid, long companyId) {

		return cpConfigurationEntrySettingPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of cp configuration entry settings matching the UUID and company.
	 *
	 * @param uuid the UUID of the cp configuration entry settings
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of cp configuration entry settings
	 * @param end the upper bound of the range of cp configuration entry settings (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching cp configuration entry settings, or an empty list if no matches were found
	 */
	@Override
	public List<CPConfigurationEntrySetting>
		getCPConfigurationEntrySettingsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<CPConfigurationEntrySetting> orderByComparator) {

		return cpConfigurationEntrySettingPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the cp configuration entry setting matching the UUID and group.
	 *
	 * @param uuid the cp configuration entry setting's UUID
	 * @param groupId the primary key of the group
	 * @return the matching cp configuration entry setting
	 * @throws PortalException if a matching cp configuration entry setting could not be found
	 */
	@Override
	public CPConfigurationEntrySetting
			getCPConfigurationEntrySettingByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return cpConfigurationEntrySettingPersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the cp configuration entry settings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPConfigurationEntrySettingModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cp configuration entry settings
	 * @param end the upper bound of the range of cp configuration entry settings (not inclusive)
	 * @return the range of cp configuration entry settings
	 */
	@Override
	public List<CPConfigurationEntrySetting> getCPConfigurationEntrySettings(
		int start, int end) {

		return cpConfigurationEntrySettingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cp configuration entry settings.
	 *
	 * @return the number of cp configuration entry settings
	 */
	@Override
	public int getCPConfigurationEntrySettingsCount() {
		return cpConfigurationEntrySettingPersistence.countAll();
	}

	/**
	 * Updates the cp configuration entry setting in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPConfigurationEntrySettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpConfigurationEntrySetting the cp configuration entry setting
	 * @return the cp configuration entry setting that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPConfigurationEntrySetting updateCPConfigurationEntrySetting(
		CPConfigurationEntrySetting cpConfigurationEntrySetting) {

		return cpConfigurationEntrySettingPersistence.update(
			cpConfigurationEntrySetting);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CPConfigurationEntrySettingLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cpConfigurationEntrySettingLocalService =
			(CPConfigurationEntrySettingLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CPConfigurationEntrySettingLocalService.class.getName();
	}

	@Override
	public CTPersistence<CPConfigurationEntrySetting> getCTPersistence() {
		return cpConfigurationEntrySettingPersistence;
	}

	@Override
	public Class<CPConfigurationEntrySetting> getModelClass() {
		return CPConfigurationEntrySetting.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<CPConfigurationEntrySetting>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			cpConfigurationEntrySettingPersistence);
	}

	protected String getModelClassName() {
		return CPConfigurationEntrySetting.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			cpConfigurationEntrySettingPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CPConfigurationEntrySettingLocalService
		cpConfigurationEntrySettingLocalService;

	@Reference
	protected CPConfigurationEntrySettingPersistence
		cpConfigurationEntrySettingPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CPConfigurationEntrySettingLocalServiceBaseImpl.class);

}
// SB-Hash:1942471155