/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.service.base;

import com.liferay.commerce.product.model.CPSpecificationOptionListTypeDefinitionRel;
import com.liferay.commerce.product.service.CPSpecificationOptionListTypeDefinitionRelLocalService;
import com.liferay.commerce.product.service.persistence.CPSpecificationOptionListTypeDefinitionRelPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cp specification option list type definition rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.product.service.impl.CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.product.service.impl.CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl
 * @generated
 */
public abstract class
	CPSpecificationOptionListTypeDefinitionRelLocalServiceBaseImpl
		extends BaseLocalServiceImpl
		implements AopService,
				   CPSpecificationOptionListTypeDefinitionRelLocalService,
				   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CPSpecificationOptionListTypeDefinitionRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.commerce.product.service.CPSpecificationOptionListTypeDefinitionRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cp specification option list type definition rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpSpecificationOptionListTypeDefinitionRel the cp specification option list type definition rel
	 * @return the cp specification option list type definition rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPSpecificationOptionListTypeDefinitionRel
		addCPSpecificationOptionListTypeDefinitionRel(
			CPSpecificationOptionListTypeDefinitionRel
				cpSpecificationOptionListTypeDefinitionRel) {

		cpSpecificationOptionListTypeDefinitionRel.setNew(true);

		return cpSpecificationOptionListTypeDefinitionRelPersistence.update(
			cpSpecificationOptionListTypeDefinitionRel);
	}

	/**
	 * Creates a new cp specification option list type definition rel with the primary key. Does not add the cp specification option list type definition rel to the database.
	 *
	 * @param CPSpecificationOptionListTypeDefinitionRelId the primary key for the new cp specification option list type definition rel
	 * @return the new cp specification option list type definition rel
	 */
	@Override
	@Transactional(enabled = false)
	public CPSpecificationOptionListTypeDefinitionRel
		createCPSpecificationOptionListTypeDefinitionRel(
			long CPSpecificationOptionListTypeDefinitionRelId) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.create(
			CPSpecificationOptionListTypeDefinitionRelId);
	}

	/**
	 * Deletes the cp specification option list type definition rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param CPSpecificationOptionListTypeDefinitionRelId the primary key of the cp specification option list type definition rel
	 * @return the cp specification option list type definition rel that was removed
	 * @throws PortalException if a cp specification option list type definition rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPSpecificationOptionListTypeDefinitionRel
			deleteCPSpecificationOptionListTypeDefinitionRel(
				long CPSpecificationOptionListTypeDefinitionRelId)
		throws PortalException {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.remove(
			CPSpecificationOptionListTypeDefinitionRelId);
	}

	/**
	 * Deletes the cp specification option list type definition rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpSpecificationOptionListTypeDefinitionRel the cp specification option list type definition rel
	 * @return the cp specification option list type definition rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPSpecificationOptionListTypeDefinitionRel
		deleteCPSpecificationOptionListTypeDefinitionRel(
			CPSpecificationOptionListTypeDefinitionRel
				cpSpecificationOptionListTypeDefinitionRel) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.remove(
			cpSpecificationOptionListTypeDefinitionRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return cpSpecificationOptionListTypeDefinitionRelPersistence.dslQuery(
			dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CPSpecificationOptionListTypeDefinitionRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPSpecificationOptionListTypeDefinitionRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPSpecificationOptionListTypeDefinitionRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public CPSpecificationOptionListTypeDefinitionRel
		fetchCPSpecificationOptionListTypeDefinitionRel(
			long CPSpecificationOptionListTypeDefinitionRelId) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			fetchByPrimaryKey(CPSpecificationOptionListTypeDefinitionRelId);
	}

	/**
	 * Returns the cp specification option list type definition rel with the primary key.
	 *
	 * @param CPSpecificationOptionListTypeDefinitionRelId the primary key of the cp specification option list type definition rel
	 * @return the cp specification option list type definition rel
	 * @throws PortalException if a cp specification option list type definition rel with the primary key could not be found
	 */
	@Override
	public CPSpecificationOptionListTypeDefinitionRel
			getCPSpecificationOptionListTypeDefinitionRel(
				long CPSpecificationOptionListTypeDefinitionRelId)
		throws PortalException {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			findByPrimaryKey(CPSpecificationOptionListTypeDefinitionRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			cpSpecificationOptionListTypeDefinitionRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			CPSpecificationOptionListTypeDefinitionRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPSpecificationOptionListTypeDefinitionRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cpSpecificationOptionListTypeDefinitionRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CPSpecificationOptionListTypeDefinitionRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPSpecificationOptionListTypeDefinitionRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			cpSpecificationOptionListTypeDefinitionRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			CPSpecificationOptionListTypeDefinitionRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPSpecificationOptionListTypeDefinitionRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl#deleteCPSpecificationOptionListTypeDefinitionRel(CPSpecificationOptionListTypeDefinitionRel) to avoid orphaned data");
		}

		return cpSpecificationOptionListTypeDefinitionRelLocalService.
			deleteCPSpecificationOptionListTypeDefinitionRel(
				(CPSpecificationOptionListTypeDefinitionRel)persistedModel);
	}

	@Override
	public BasePersistence<CPSpecificationOptionListTypeDefinitionRel>
		getBasePersistence() {

		return cpSpecificationOptionListTypeDefinitionRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.
			findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the cp specification option list type definition rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.product.model.impl.CPSpecificationOptionListTypeDefinitionRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cp specification option list type definition rels
	 * @param end the upper bound of the range of cp specification option list type definition rels (not inclusive)
	 * @return the range of cp specification option list type definition rels
	 */
	@Override
	public List<CPSpecificationOptionListTypeDefinitionRel>
		getCPSpecificationOptionListTypeDefinitionRels(int start, int end) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.findAll(
			start, end);
	}

	/**
	 * Returns the number of cp specification option list type definition rels.
	 *
	 * @return the number of cp specification option list type definition rels
	 */
	@Override
	public int getCPSpecificationOptionListTypeDefinitionRelsCount() {
		return cpSpecificationOptionListTypeDefinitionRelPersistence.countAll();
	}

	/**
	 * Updates the cp specification option list type definition rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPSpecificationOptionListTypeDefinitionRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpSpecificationOptionListTypeDefinitionRel the cp specification option list type definition rel
	 * @return the cp specification option list type definition rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPSpecificationOptionListTypeDefinitionRel
		updateCPSpecificationOptionListTypeDefinitionRel(
			CPSpecificationOptionListTypeDefinitionRel
				cpSpecificationOptionListTypeDefinitionRel) {

		return cpSpecificationOptionListTypeDefinitionRelPersistence.update(
			cpSpecificationOptionListTypeDefinitionRel);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CPSpecificationOptionListTypeDefinitionRelLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cpSpecificationOptionListTypeDefinitionRelLocalService =
			(CPSpecificationOptionListTypeDefinitionRelLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CPSpecificationOptionListTypeDefinitionRelLocalService.class.
			getName();
	}

	@Override
	public CTPersistence<CPSpecificationOptionListTypeDefinitionRel>
		getCTPersistence() {

		return cpSpecificationOptionListTypeDefinitionRelPersistence;
	}

	@Override
	public Class<CPSpecificationOptionListTypeDefinitionRel> getModelClass() {
		return CPSpecificationOptionListTypeDefinitionRel.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction
				<CTPersistence<CPSpecificationOptionListTypeDefinitionRel>, R,
				 E> updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			cpSpecificationOptionListTypeDefinitionRelPersistence);
	}

	protected String getModelClassName() {
		return CPSpecificationOptionListTypeDefinitionRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			cpSpecificationOptionListTypeDefinitionRelPersistence.
				getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CPSpecificationOptionListTypeDefinitionRelLocalService
		cpSpecificationOptionListTypeDefinitionRelLocalService;

	@Reference
	protected CPSpecificationOptionListTypeDefinitionRelPersistence
		cpSpecificationOptionListTypeDefinitionRelPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CPSpecificationOptionListTypeDefinitionRelLocalServiceBaseImpl.class);

}
// SB-Hash:-357970044