/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.tax.service.base;

import com.liferay.commerce.tax.model.CommerceTaxCategoryMapping;
import com.liferay.commerce.tax.service.CommerceTaxCategoryMappingLocalService;
import com.liferay.commerce.tax.service.persistence.CommerceTaxCategoryMappingPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the commerce tax category mapping local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.tax.service.impl.CommerceTaxCategoryMappingLocalServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.tax.service.impl.CommerceTaxCategoryMappingLocalServiceImpl
 * @generated
 */
public abstract class CommerceTaxCategoryMappingLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CommerceTaxCategoryMappingLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceTaxCategoryMappingLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.commerce.tax.service.CommerceTaxCategoryMappingLocalServiceUtil</code>.
	 */

	/**
	 * Adds the commerce tax category mapping to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceTaxCategoryMappingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceTaxCategoryMapping the commerce tax category mapping
	 * @return the commerce tax category mapping that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceTaxCategoryMapping addCommerceTaxCategoryMapping(
		CommerceTaxCategoryMapping commerceTaxCategoryMapping) {

		commerceTaxCategoryMapping.setNew(true);

		return commerceTaxCategoryMappingPersistence.update(
			commerceTaxCategoryMapping);
	}

	/**
	 * Creates a new commerce tax category mapping with the primary key. Does not add the commerce tax category mapping to the database.
	 *
	 * @param commerceTaxCategoryMappingId the primary key for the new commerce tax category mapping
	 * @return the new commerce tax category mapping
	 */
	@Override
	@Transactional(enabled = false)
	public CommerceTaxCategoryMapping createCommerceTaxCategoryMapping(
		long commerceTaxCategoryMappingId) {

		return commerceTaxCategoryMappingPersistence.create(
			commerceTaxCategoryMappingId);
	}

	/**
	 * Deletes the commerce tax category mapping with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceTaxCategoryMappingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceTaxCategoryMappingId the primary key of the commerce tax category mapping
	 * @return the commerce tax category mapping that was removed
	 * @throws PortalException if a commerce tax category mapping with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceTaxCategoryMapping deleteCommerceTaxCategoryMapping(
			long commerceTaxCategoryMappingId)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.remove(
			commerceTaxCategoryMappingId);
	}

	/**
	 * Deletes the commerce tax category mapping from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceTaxCategoryMappingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceTaxCategoryMapping the commerce tax category mapping
	 * @return the commerce tax category mapping that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceTaxCategoryMapping deleteCommerceTaxCategoryMapping(
		CommerceTaxCategoryMapping commerceTaxCategoryMapping) {

		return commerceTaxCategoryMappingPersistence.remove(
			commerceTaxCategoryMapping);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return commerceTaxCategoryMappingPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CommerceTaxCategoryMapping.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return commerceTaxCategoryMappingPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.tax.model.impl.CommerceTaxCategoryMappingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return commerceTaxCategoryMappingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.tax.model.impl.CommerceTaxCategoryMappingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return commerceTaxCategoryMappingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return commerceTaxCategoryMappingPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return commerceTaxCategoryMappingPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CommerceTaxCategoryMapping fetchCommerceTaxCategoryMapping(
		long commerceTaxCategoryMappingId) {

		return commerceTaxCategoryMappingPersistence.fetchByPrimaryKey(
			commerceTaxCategoryMappingId);
	}

	/**
	 * Returns the commerce tax category mapping matching the UUID and group.
	 *
	 * @param uuid the commerce tax category mapping's UUID
	 * @param groupId the primary key of the group
	 * @return the matching commerce tax category mapping, or <code>null</code> if a matching commerce tax category mapping could not be found
	 */
	@Override
	public CommerceTaxCategoryMapping
		fetchCommerceTaxCategoryMappingByUuidAndGroupId(
			String uuid, long groupId) {

		return commerceTaxCategoryMappingPersistence.fetchByUUID_G(
			uuid, groupId);
	}

	@Override
	public CommerceTaxCategoryMapping
		fetchCommerceTaxCategoryMappingByExternalReferenceCode(
			String externalReferenceCode, long companyId) {

		return commerceTaxCategoryMappingPersistence.fetchByERC_C(
			externalReferenceCode, companyId);
	}

	@Override
	public CommerceTaxCategoryMapping
			getCommerceTaxCategoryMappingByExternalReferenceCode(
				String externalReferenceCode, long companyId)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.findByERC_C(
			externalReferenceCode, companyId);
	}

	/**
	 * Returns the commerce tax category mapping with the primary key.
	 *
	 * @param commerceTaxCategoryMappingId the primary key of the commerce tax category mapping
	 * @return the commerce tax category mapping
	 * @throws PortalException if a commerce tax category mapping with the primary key could not be found
	 */
	@Override
	public CommerceTaxCategoryMapping getCommerceTaxCategoryMapping(
			long commerceTaxCategoryMappingId)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.findByPrimaryKey(
			commerceTaxCategoryMappingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			commerceTaxCategoryMappingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommerceTaxCategoryMapping.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceTaxCategoryMappingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			commerceTaxCategoryMappingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CommerceTaxCategoryMapping.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceTaxCategoryMappingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			commerceTaxCategoryMappingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommerceTaxCategoryMapping.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceTaxCategoryMappingId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<CommerceTaxCategoryMapping>() {

				@Override
				public void performAction(
						CommerceTaxCategoryMapping commerceTaxCategoryMapping)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, commerceTaxCategoryMapping);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					CommerceTaxCategoryMapping.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CommerceTaxCategoryMappingLocalServiceImpl#deleteCommerceTaxCategoryMapping(CommerceTaxCategoryMapping) to avoid orphaned data");
		}

		return commerceTaxCategoryMappingLocalService.
			deleteCommerceTaxCategoryMapping(
				(CommerceTaxCategoryMapping)persistedModel);
	}

	@Override
	public BasePersistence<CommerceTaxCategoryMapping> getBasePersistence() {
		return commerceTaxCategoryMappingPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the commerce tax category mappings matching the UUID and company.
	 *
	 * @param uuid the UUID of the commerce tax category mappings
	 * @param companyId the primary key of the company
	 * @return the matching commerce tax category mappings, or an empty list if no matches were found
	 */
	@Override
	public List<CommerceTaxCategoryMapping>
		getCommerceTaxCategoryMappingsByUuidAndCompanyId(
			String uuid, long companyId) {

		return commerceTaxCategoryMappingPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of commerce tax category mappings matching the UUID and company.
	 *
	 * @param uuid the UUID of the commerce tax category mappings
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of commerce tax category mappings
	 * @param end the upper bound of the range of commerce tax category mappings (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching commerce tax category mappings, or an empty list if no matches were found
	 */
	@Override
	public List<CommerceTaxCategoryMapping>
		getCommerceTaxCategoryMappingsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<CommerceTaxCategoryMapping> orderByComparator) {

		return commerceTaxCategoryMappingPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the commerce tax category mapping matching the UUID and group.
	 *
	 * @param uuid the commerce tax category mapping's UUID
	 * @param groupId the primary key of the group
	 * @return the matching commerce tax category mapping
	 * @throws PortalException if a matching commerce tax category mapping could not be found
	 */
	@Override
	public CommerceTaxCategoryMapping
			getCommerceTaxCategoryMappingByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return commerceTaxCategoryMappingPersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the commerce tax category mappings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.tax.model.impl.CommerceTaxCategoryMappingModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of commerce tax category mappings
	 * @param end the upper bound of the range of commerce tax category mappings (not inclusive)
	 * @return the range of commerce tax category mappings
	 */
	@Override
	public List<CommerceTaxCategoryMapping> getCommerceTaxCategoryMappings(
		int start, int end) {

		return commerceTaxCategoryMappingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of commerce tax category mappings.
	 *
	 * @return the number of commerce tax category mappings
	 */
	@Override
	public int getCommerceTaxCategoryMappingsCount() {
		return commerceTaxCategoryMappingPersistence.countAll();
	}

	/**
	 * Updates the commerce tax category mapping in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceTaxCategoryMappingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceTaxCategoryMapping the commerce tax category mapping
	 * @return the commerce tax category mapping that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceTaxCategoryMapping updateCommerceTaxCategoryMapping(
		CommerceTaxCategoryMapping commerceTaxCategoryMapping) {

		return commerceTaxCategoryMappingPersistence.update(
			commerceTaxCategoryMapping);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CommerceTaxCategoryMappingLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		commerceTaxCategoryMappingLocalService =
			(CommerceTaxCategoryMappingLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceTaxCategoryMappingLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceTaxCategoryMapping.class;
	}

	protected String getModelClassName() {
		return CommerceTaxCategoryMapping.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			commerceTaxCategoryMappingPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CommerceTaxCategoryMappingLocalService
		commerceTaxCategoryMappingLocalService;

	@Reference
	protected CommerceTaxCategoryMappingPersistence
		commerceTaxCategoryMappingPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CommerceTaxCategoryMappingLocalServiceBaseImpl.class);

}
// SB-Hash:-515149527