/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.list.type.model.impl;

import com.liferay.list.type.model.ListTypeEntry;
import com.liferay.list.type.service.ListTypeEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ListTypeEntry service. Represents a row in the &quot;ListTypeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ListTypeEntryImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see ListTypeEntryImpl
 * @see ListTypeEntry
 * @generated
 */
public abstract class ListTypeEntryBaseImpl
	extends ListTypeEntryModelImpl implements ListTypeEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a list type entry model instance should use the <code>ListTypeEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ListTypeEntryLocalServiceUtil.addListTypeEntry(this);
		}
		else {
			ListTypeEntryLocalServiceUtil.updateListTypeEntry(this);
		}
	}

}
// SB-Hash:-1725671711