/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat700.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CacheDisabledEntry service. Represents a row in the &quot;CacheDisabledEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.compat700.model.impl.CacheDisabledEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.compat700.model.impl.CacheDisabledEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CacheDisabledEntry
 * @generated
 */
@ProviderType
public interface CacheDisabledEntryModel extends BaseModel<CacheDisabledEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cache disabled entry model instance should use the {@link CacheDisabledEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this cache disabled entry.
	 *
	 * @return the primary key of this cache disabled entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cache disabled entry.
	 *
	 * @param primaryKey the primary key of this cache disabled entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cache disabled entry ID of this cache disabled entry.
	 *
	 * @return the cache disabled entry ID of this cache disabled entry
	 */
	public long getCacheDisabledEntryId();

	/**
	 * Sets the cache disabled entry ID of this cache disabled entry.
	 *
	 * @param cacheDisabledEntryId the cache disabled entry ID of this cache disabled entry
	 */
	public void setCacheDisabledEntryId(long cacheDisabledEntryId);

	/**
	 * Returns the name of this cache disabled entry.
	 *
	 * @return the name of this cache disabled entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cache disabled entry.
	 *
	 * @param name the name of this cache disabled entry
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CacheDisabledEntry cacheDisabledEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CacheDisabledEntry> toCacheModel();

	@Override
	public CacheDisabledEntry toEscapedModel();

	@Override
	public CacheDisabledEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}
// SB-Hash:-998994987