/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat700.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LikeFinderEntry service. Represents a row in the &quot;LikeFinderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.compat700.model.impl.LikeFinderEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.compat700.model.impl.LikeFinderEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LikeFinderEntry
 * @generated
 */
@ProviderType
public interface LikeFinderEntryModel
	extends BaseModel<LikeFinderEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a like finder entry model instance should use the {@link LikeFinderEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this like finder entry.
	 *
	 * @return the primary key of this like finder entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this like finder entry.
	 *
	 * @param primaryKey the primary key of this like finder entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the like finder entry ID of this like finder entry.
	 *
	 * @return the like finder entry ID of this like finder entry
	 */
	public long getLikeFinderEntryId();

	/**
	 * Sets the like finder entry ID of this like finder entry.
	 *
	 * @param likeFinderEntryId the like finder entry ID of this like finder entry
	 */
	public void setLikeFinderEntryId(long likeFinderEntryId);

	/**
	 * Returns the company ID of this like finder entry.
	 *
	 * @return the company ID of this like finder entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this like finder entry.
	 *
	 * @param companyId the company ID of this like finder entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the owner ID of this like finder entry.
	 *
	 * @return the owner ID of this like finder entry
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this like finder entry.
	 *
	 * @param ownerId the owner ID of this like finder entry
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the owner type of this like finder entry.
	 *
	 * @return the owner type of this like finder entry
	 */
	public int getOwnerType();

	/**
	 * Sets the owner type of this like finder entry.
	 *
	 * @param ownerType the owner type of this like finder entry
	 */
	public void setOwnerType(int ownerType);

	/**
	 * Returns the portlet ID of this like finder entry.
	 *
	 * @return the portlet ID of this like finder entry
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this like finder entry.
	 *
	 * @param portletId the portlet ID of this like finder entry
	 */
	public void setPortletId(String portletId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LikeFinderEntry likeFinderEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LikeFinderEntry> toCacheModel();

	@Override
	public LikeFinderEntry toEscapedModel();

	@Override
	public LikeFinderEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}
// SB-Hash:970749346