/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.DefinedDefaultOrderEntry;
import com.liferay.portal.tools.service.builder.test.service.DefinedDefaultOrderEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.DefinedDefaultOrderEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.DefinedDefaultOrderEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the defined default order entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.DefinedDefaultOrderEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.DefinedDefaultOrderEntryLocalServiceImpl
 * @generated
 */
public abstract class DefinedDefaultOrderEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements DefinedDefaultOrderEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DefinedDefaultOrderEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DefinedDefaultOrderEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the defined default order entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinedDefaultOrderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definedDefaultOrderEntry the defined default order entry
	 * @return the defined default order entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DefinedDefaultOrderEntry addDefinedDefaultOrderEntry(
		DefinedDefaultOrderEntry definedDefaultOrderEntry) {

		definedDefaultOrderEntry.setNew(true);

		return definedDefaultOrderEntryPersistence.update(
			definedDefaultOrderEntry);
	}

	/**
	 * Creates a new defined default order entry with the primary key. Does not add the defined default order entry to the database.
	 *
	 * @param definedDefaultOrderEntryId the primary key for the new defined default order entry
	 * @return the new defined default order entry
	 */
	@Override
	@Transactional(enabled = false)
	public DefinedDefaultOrderEntry createDefinedDefaultOrderEntry(
		long definedDefaultOrderEntryId) {

		return definedDefaultOrderEntryPersistence.create(
			definedDefaultOrderEntryId);
	}

	/**
	 * Deletes the defined default order entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinedDefaultOrderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definedDefaultOrderEntryId the primary key of the defined default order entry
	 * @return the defined default order entry that was removed
	 * @throws PortalException if a defined default order entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DefinedDefaultOrderEntry deleteDefinedDefaultOrderEntry(
			long definedDefaultOrderEntryId)
		throws PortalException {

		return definedDefaultOrderEntryPersistence.remove(
			definedDefaultOrderEntryId);
	}

	/**
	 * Deletes the defined default order entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinedDefaultOrderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definedDefaultOrderEntry the defined default order entry
	 * @return the defined default order entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DefinedDefaultOrderEntry deleteDefinedDefaultOrderEntry(
		DefinedDefaultOrderEntry definedDefaultOrderEntry) {

		return definedDefaultOrderEntryPersistence.remove(
			definedDefaultOrderEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return definedDefaultOrderEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DefinedDefaultOrderEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return definedDefaultOrderEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DefinedDefaultOrderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return definedDefaultOrderEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DefinedDefaultOrderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return definedDefaultOrderEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return definedDefaultOrderEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return definedDefaultOrderEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DefinedDefaultOrderEntry fetchDefinedDefaultOrderEntry(
		long definedDefaultOrderEntryId) {

		return definedDefaultOrderEntryPersistence.fetchByPrimaryKey(
			definedDefaultOrderEntryId);
	}

	/**
	 * Returns the defined default order entry with the primary key.
	 *
	 * @param definedDefaultOrderEntryId the primary key of the defined default order entry
	 * @return the defined default order entry
	 * @throws PortalException if a defined default order entry with the primary key could not be found
	 */
	@Override
	public DefinedDefaultOrderEntry getDefinedDefaultOrderEntry(
			long definedDefaultOrderEntryId)
		throws PortalException {

		return definedDefaultOrderEntryPersistence.findByPrimaryKey(
			definedDefaultOrderEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			definedDefaultOrderEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DefinedDefaultOrderEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"definedDefaultOrderEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			definedDefaultOrderEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DefinedDefaultOrderEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"definedDefaultOrderEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			definedDefaultOrderEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DefinedDefaultOrderEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"definedDefaultOrderEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return definedDefaultOrderEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement DefinedDefaultOrderEntryLocalServiceImpl#deleteDefinedDefaultOrderEntry(DefinedDefaultOrderEntry) to avoid orphaned data");
		}

		return definedDefaultOrderEntryLocalService.
			deleteDefinedDefaultOrderEntry(
				(DefinedDefaultOrderEntry)persistedModel);
	}

	@Override
	public BasePersistence<DefinedDefaultOrderEntry> getBasePersistence() {
		return definedDefaultOrderEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return definedDefaultOrderEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the defined default order entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DefinedDefaultOrderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of defined default order entries
	 * @param end the upper bound of the range of defined default order entries (not inclusive)
	 * @return the range of defined default order entries
	 */
	@Override
	public List<DefinedDefaultOrderEntry> getDefinedDefaultOrderEntries(
		int start, int end) {

		return definedDefaultOrderEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of defined default order entries.
	 *
	 * @return the number of defined default order entries
	 */
	@Override
	public int getDefinedDefaultOrderEntriesCount() {
		return definedDefaultOrderEntryPersistence.countAll();
	}

	/**
	 * Updates the defined default order entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinedDefaultOrderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definedDefaultOrderEntry the defined default order entry
	 * @return the defined default order entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DefinedDefaultOrderEntry updateDefinedDefaultOrderEntry(
		DefinedDefaultOrderEntry definedDefaultOrderEntry) {

		return definedDefaultOrderEntryPersistence.update(
			definedDefaultOrderEntry);
	}

	/**
	 * Returns the defined default order entry local service.
	 *
	 * @return the defined default order entry local service
	 */
	public DefinedDefaultOrderEntryLocalService
		getDefinedDefaultOrderEntryLocalService() {

		return definedDefaultOrderEntryLocalService;
	}

	/**
	 * Sets the defined default order entry local service.
	 *
	 * @param definedDefaultOrderEntryLocalService the defined default order entry local service
	 */
	public void setDefinedDefaultOrderEntryLocalService(
		DefinedDefaultOrderEntryLocalService
			definedDefaultOrderEntryLocalService) {

		this.definedDefaultOrderEntryLocalService =
			definedDefaultOrderEntryLocalService;
	}

	/**
	 * Returns the defined default order entry persistence.
	 *
	 * @return the defined default order entry persistence
	 */
	public DefinedDefaultOrderEntryPersistence
		getDefinedDefaultOrderEntryPersistence() {

		return definedDefaultOrderEntryPersistence;
	}

	/**
	 * Sets the defined default order entry persistence.
	 *
	 * @param definedDefaultOrderEntryPersistence the defined default order entry persistence
	 */
	public void setDefinedDefaultOrderEntryPersistence(
		DefinedDefaultOrderEntryPersistence
			definedDefaultOrderEntryPersistence) {

		this.definedDefaultOrderEntryPersistence =
			definedDefaultOrderEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		DefinedDefaultOrderEntryLocalServiceUtil.setService(
			definedDefaultOrderEntryLocalService);
	}

	public void destroy() {
		DefinedDefaultOrderEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DefinedDefaultOrderEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DefinedDefaultOrderEntry.class;
	}

	protected String getModelClassName() {
		return DefinedDefaultOrderEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			definedDefaultOrderEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = DefinedDefaultOrderEntryLocalService.class)
	protected DefinedDefaultOrderEntryLocalService
		definedDefaultOrderEntryLocalService;

	@BeanReference(type = DefinedDefaultOrderEntryPersistence.class)
	protected DefinedDefaultOrderEntryPersistence
		definedDefaultOrderEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		DefinedDefaultOrderEntryLocalServiceBaseImpl.class);

}
// SB-Hash:-760476615