/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.util.InfrastructureUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.service.GenericMethodsEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.GenericMethodsEntryLocalServiceUtil;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the generic methods entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.GenericMethodsEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.GenericMethodsEntryLocalServiceImpl
 * @generated
 */
public abstract class GenericMethodsEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements GenericMethodsEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GenericMethodsEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GenericMethodsEntryLocalServiceUtil</code>.
	 */

	/**
	 * Returns the generic methods entry local service.
	 *
	 * @return the generic methods entry local service
	 */
	public GenericMethodsEntryLocalService
		getGenericMethodsEntryLocalService() {

		return genericMethodsEntryLocalService;
	}

	/**
	 * Sets the generic methods entry local service.
	 *
	 * @param genericMethodsEntryLocalService the generic methods entry local service
	 */
	public void setGenericMethodsEntryLocalService(
		GenericMethodsEntryLocalService genericMethodsEntryLocalService) {

		this.genericMethodsEntryLocalService = genericMethodsEntryLocalService;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		GenericMethodsEntryLocalServiceUtil.setService(
			genericMethodsEntryLocalService);
	}

	public void destroy() {
		GenericMethodsEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GenericMethodsEntryLocalService.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = InfrastructureUtil.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = GenericMethodsEntryLocalService.class)
	protected GenericMethodsEntryLocalService genericMethodsEntryLocalService;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		GenericMethodsEntryLocalServiceBaseImpl.class);

}
// SB-Hash:-1572629865