#
# Application
#

liferay.customer.business.event.cron=${LIFERAY_CUSTOMER_BUSINESS_EVENT_CRON}
liferay.customer.gcf.base.url=${LIFERAY_CUSTOMER_GCF_BASE_URL}
liferay.customer.gcf.composable.service.account.key=${LIFERAY_CUSTOMER_GCF_COMPOSABLE_SERVICE_ACCOUNT_KEY}
liferay.customer.gcf.customer.service.account.key=${LIFERAY_CUSTOMER_GCF_CUSTOMER_SERVICE_ACCOUNT_KEY}
liferay.customer.gcs.bucket.name=${LIFERAY_CUSTOMER_GCS_BUCKET_NAME}
liferay.customer.gcs.service.account.key=${LIFERAY_CUSTOMER_GCS_SERVICE_ACCOUNT_KEY}
liferay.customer.jira.api.email.address=${LIFERAY_CUSTOMER_JIRA_API_EMAIL_ADDRESS}
liferay.customer.jira.api.token=${LIFERAY_CUSTOMER_JIRA_API_TOKEN}
liferay.customer.jira.security.vulnerability.field.affected.versions.details=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTED_VERSIONS_DETAILS}
liferay.customer.jira.security.vulnerability.field.affects=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTS}
liferay.customer.jira.security.vulnerability.field.categories=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CATEGORIES}
liferay.customer.jira.security.vulnerability.field.customer.portal.description=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_DESCRIPTION}
liferay.customer.jira.security.vulnerability.field.customer.portal.summary=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_SUMMARY}
liferay.customer.jira.security.vulnerability.field.customer.publishing.date=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PUBLISHING_DATE}
liferay.customer.jira.security.vulnerability.field.cve.ids=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVE_IDS}
liferay.customer.jira.security.vulnerability.field.cvss.base.score=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_BASE_SCORE}
liferay.customer.jira.security.vulnerability.field.cvss.vector.string=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_VECTOR_STRING}
liferay.customer.jira.security.vulnerability.field.cwe.ids=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CWE_IDS}
liferay.customer.jira.security.vulnerability.field.fix.versions=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_FIX_VERSIONS}
liferay.customer.jira.security.vulnerability.field.issue.classification=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_ISSUE_CLASSIFICATION}
liferay.customer.jira.security.vulnerability.field.partner.publishing.date=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_PARTNER_PUBLISHING_DATE}
liferay.customer.jira.security.vulnerability.field.publishing.status=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_PUBLISHING_STATUS}
liferay.customer.jira.security.vulnerability.field.severity=${LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_SEVERITY}
liferay.customer.jira.security.vulnerability.project=LSV
liferay.customer.jira.service.affected.versions.cache.eviction.cron=${LIFERAY_CUSTOMER_JIRA_SERVICE_AFFECTED_VERSIONS_CACHE_EVICTION_CRON}
liferay.customer.jira.service.issues.cache.eviction.cron=${LIFERAY_CUSTOMER_JIRA_SERVICE_ISSUES_CACHE_EVICTION_CRON}
liferay.customer.jira.support.fls.portal.url=${LIFERAY_CUSTOMER_JIRA_SUPPORT_FLS_PORTAL_URL}
liferay.customer.jira.support.fls.project=${LIFERAY_CUSTOMER_JIRA_SUPPORT_FLS_PROJECT}
liferay.customer.jira.support.hc.field.business.event=${LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_BUSINESS_EVENT}
liferay.customer.jira.support.hc.field.organization=${LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_ORGANIZATION}
liferay.customer.jira.support.hc.field.request.type=${LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_REQUEST_TYPE}
liferay.customer.jira.support.hc.portal.url=${LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_PORTAL_URL}
liferay.customer.jira.support.hc.project=${LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_PROJECT}
liferay.customer.jira.url=${LIFERAY_CUSTOMER_JIRA_URL}
liferay.customer.jira.workspace.id=${LIFERAY_CUSTOMER_JIRA_WORKSPACE_ID}
liferay.customer.koroneiki.auth.token=${LIFERAY_CUSTOMER_KORONEIKI_AUTH_TOKEN}
liferay.customer.koroneiki.url=${LIFERAY_CUSTOMER_KORONEIKI_URL}
liferay.customer.notification.subscription.from.email=${LIFERAY_CUSTOMER_NOTIFICATION_SUBSCRIPTION_FROM_EMAIL}
liferay.customer.notification.subscription.from.name=${LIFERAY_CUSTOMER_NOTIFICATION_SUBSCRIPTION_FROM_NAME}
liferay.customer.portal.url=${LIFERAY_CUSTOMER_PORTAL_URL}
liferay.customer.version.list.type.cron=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_CRON}
liferay.customer.version.list.type.dxp.major.erc=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MAJOR_ERC}
liferay.customer.version.list.type.dxp.minor.erc=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MINOR_ERC}
liferay.customer.version.list.type.dxp.minor.portal.major.erc=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MINOR_PORTAL_MAJOR_ERC}
liferay.customer.version.list.type.portal.major.versions=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_PORTAL_MAJOR_VERSIONS}
liferay.customer.version.list.type.releases.url=${LIFERAY_CUSTOMER_VERSION_LIST_TYPE_RELEASES_URL}

#
# OAuth
#

liferay-customer-etc-spring-boot-oahs.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-spring-boot-oahs,\
    liferay-customer-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081
spring.boot.web.client.max.in.memory.size=${SPRING_BOOT_WEB_CLIENT_MAX_IN_MEMORY_SIZE}