##
## Test Suites
##

    modified.files.includes[relevant][layout-functional-rule]=**

    modified.files.includes[relevant][layout-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=\
        layout-functional-rule,\
        layout-java-rule

    test.batch.names[relevant][layout-functional-rule]=\
        functional-upgrade-tomcat90-mysql57

    test.batch.names[relevant][layout-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][layout-java-rule]=\
        apps/headless/headless-admin-site/**/*Test.java,\
        apps/layout/**/*Test.java,\
        apps/portal/portal-events-test/src/testIntegration/**/ServicePreActionTest.java,\
        apps/segments/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][layout-java-rule]=\
        apps/layout/**/*Test.java

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][layout-functional-rule]=\
        (portal.acceptance == true)

##
## Testray
##

    testray.main.component.name=Content Pages