##
## Test Suites
##

    modified.files.includes[relevant][knowledge-base-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=knowledge-base-java-rule

    test.batch.names[relevant][knowledge-base-java-rule]=\
<<<<<<< HEAD
        modules-integration-postgresql155,\
=======
<<<<<<< HEAD
        modules-integration-mysql57,\
=======
        modules-integration-postgresql163,\
>>>>>>> 8963b385431f4 (LPD-50277 Update to postgresql163)
>>>>>>> ca7154f2c958e (LPD-50277 Update to postgresql163)
        modules-unit

    #
    # Relevant
    #

<<<<<<< HEAD
    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155][relevant][knowledge-base-java-rule]=\
=======
<<<<<<< HEAD
    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][knowledge-base-java-rule]=\
=======
    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][knowledge-base-java-rule]=\
>>>>>>> 8963b385431f4 (LPD-50277 Update to postgresql163)
>>>>>>> ca7154f2c958e (LPD-50277 Update to postgresql163)
        apps/knowledge-base/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][knowledge-base-java-rule]=\
        apps/knowledge-base/**/*Test.java

##
## Testray
##

    testray.main.component.name=Knowledge Base