/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.compat710.model.ERCVersionedEntry;
import com.liferay.portal.tools.service.builder.test.compat710.service.ERCVersionedEntryLocalService;
import com.liferay.portal.tools.service.builder.test.compat710.service.ERCVersionedEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.compat710.service.persistence.ERCVersionedEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the erc versioned entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.compat710.service.impl.ERCVersionedEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.compat710.service.impl.ERCVersionedEntryLocalServiceImpl
 * @generated
 */
public abstract class ERCVersionedEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements ERCVersionedEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ERCVersionedEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ERCVersionedEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the erc versioned entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ERCVersionedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ercVersionedEntry the erc versioned entry
	 * @return the erc versioned entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ERCVersionedEntry addERCVersionedEntry(
		ERCVersionedEntry ercVersionedEntry) {

		ercVersionedEntry.setNew(true);

		return ercVersionedEntryPersistence.update(ercVersionedEntry);
	}

	/**
	 * Creates a new erc versioned entry with the primary key. Does not add the erc versioned entry to the database.
	 *
	 * @param ercVersionedEntryId the primary key for the new erc versioned entry
	 * @return the new erc versioned entry
	 */
	@Override
	@Transactional(enabled = false)
	public ERCVersionedEntry createERCVersionedEntry(long ercVersionedEntryId) {
		return ercVersionedEntryPersistence.create(ercVersionedEntryId);
	}

	/**
	 * Deletes the erc versioned entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ERCVersionedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ercVersionedEntryId the primary key of the erc versioned entry
	 * @return the erc versioned entry that was removed
	 * @throws PortalException if a erc versioned entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ERCVersionedEntry deleteERCVersionedEntry(long ercVersionedEntryId)
		throws PortalException {

		return ercVersionedEntryPersistence.remove(ercVersionedEntryId);
	}

	/**
	 * Deletes the erc versioned entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ERCVersionedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ercVersionedEntry the erc versioned entry
	 * @return the erc versioned entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ERCVersionedEntry deleteERCVersionedEntry(
		ERCVersionedEntry ercVersionedEntry) {

		return ercVersionedEntryPersistence.remove(ercVersionedEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ERCVersionedEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ercVersionedEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat710.model.impl.ERCVersionedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return ercVersionedEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat710.model.impl.ERCVersionedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return ercVersionedEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ercVersionedEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return ercVersionedEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ERCVersionedEntry fetchERCVersionedEntry(long ercVersionedEntryId) {
		return ercVersionedEntryPersistence.fetchByPrimaryKey(
			ercVersionedEntryId);
	}

	/**
	 * Returns the erc versioned entry matching the UUID and group.
	 *
	 * @param uuid the erc versioned entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching erc versioned entry, or <code>null</code> if a matching erc versioned entry could not be found
	 */
	@Override
	public ERCVersionedEntry fetchERCVersionedEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return ercVersionedEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	@Deprecated
	@Override
	public ERCVersionedEntry fetchERCVersionedEntryByExternalReferenceCode(
		long groupId, String externalReferenceCode) {

		return ercVersionedEntryPersistence.fetchByG_ERC(
			groupId, externalReferenceCode);
	}

	@Deprecated
	@Override
	public ERCVersionedEntry fetchERCVersionedEntryByReferenceCode(
		long groupId, String externalReferenceCode) {

		return fetchERCVersionedEntryByExternalReferenceCode(
			groupId, externalReferenceCode);
	}

	@Deprecated
	@Override
	public ERCVersionedEntry getERCVersionedEntryByExternalReferenceCode(
			long groupId, String externalReferenceCode)
		throws PortalException {

		return ercVersionedEntryPersistence.findByG_ERC(
			groupId, externalReferenceCode);
	}

	/**
	 * Returns the erc versioned entry with the primary key.
	 *
	 * @param ercVersionedEntryId the primary key of the erc versioned entry
	 * @return the erc versioned entry
	 * @throws PortalException if a erc versioned entry with the primary key could not be found
	 */
	@Override
	public ERCVersionedEntry getERCVersionedEntry(long ercVersionedEntryId)
		throws PortalException {

		return ercVersionedEntryPersistence.findByPrimaryKey(
			ercVersionedEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			ercVersionedEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ERCVersionedEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ercVersionedEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			ercVersionedEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ERCVersionedEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"ercVersionedEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			ercVersionedEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ERCVersionedEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ercVersionedEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return ercVersionedEntryLocalService.deleteERCVersionedEntry(
			(ERCVersionedEntry)persistedModel);
	}

	public BasePersistence<ERCVersionedEntry> getBasePersistence() {
		return ercVersionedEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return ercVersionedEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the erc versioned entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the erc versioned entries
	 * @param companyId the primary key of the company
	 * @return the matching erc versioned entries, or an empty list if no matches were found
	 */
	@Override
	public List<ERCVersionedEntry> getERCVersionedEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return ercVersionedEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of erc versioned entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the erc versioned entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of erc versioned entries
	 * @param end the upper bound of the range of erc versioned entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching erc versioned entries, or an empty list if no matches were found
	 */
	@Override
	public List<ERCVersionedEntry> getERCVersionedEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ERCVersionedEntry> orderByComparator) {

		return ercVersionedEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the erc versioned entry matching the UUID and group.
	 *
	 * @param uuid the erc versioned entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching erc versioned entry
	 * @throws PortalException if a matching erc versioned entry could not be found
	 */
	@Override
	public ERCVersionedEntry getERCVersionedEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return ercVersionedEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the erc versioned entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat710.model.impl.ERCVersionedEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of erc versioned entries
	 * @param end the upper bound of the range of erc versioned entries (not inclusive)
	 * @return the range of erc versioned entries
	 */
	@Override
	public List<ERCVersionedEntry> getERCVersionedEntries(int start, int end) {
		return ercVersionedEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of erc versioned entries.
	 *
	 * @return the number of erc versioned entries
	 */
	@Override
	public int getERCVersionedEntriesCount() {
		return ercVersionedEntryPersistence.countAll();
	}

	/**
	 * Updates the erc versioned entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ERCVersionedEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ercVersionedEntry the erc versioned entry
	 * @return the erc versioned entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ERCVersionedEntry updateERCVersionedEntry(
		ERCVersionedEntry ercVersionedEntry) {

		return ercVersionedEntryPersistence.update(ercVersionedEntry);
	}

	/**
	 * Returns the erc versioned entry local service.
	 *
	 * @return the erc versioned entry local service
	 */
	public ERCVersionedEntryLocalService getERCVersionedEntryLocalService() {
		return ercVersionedEntryLocalService;
	}

	/**
	 * Sets the erc versioned entry local service.
	 *
	 * @param ercVersionedEntryLocalService the erc versioned entry local service
	 */
	public void setERCVersionedEntryLocalService(
		ERCVersionedEntryLocalService ercVersionedEntryLocalService) {

		this.ercVersionedEntryLocalService = ercVersionedEntryLocalService;
	}

	/**
	 * Returns the erc versioned entry persistence.
	 *
	 * @return the erc versioned entry persistence
	 */
	public ERCVersionedEntryPersistence getERCVersionedEntryPersistence() {
		return ercVersionedEntryPersistence;
	}

	/**
	 * Sets the erc versioned entry persistence.
	 *
	 * @param ercVersionedEntryPersistence the erc versioned entry persistence
	 */
	public void setERCVersionedEntryPersistence(
		ERCVersionedEntryPersistence ercVersionedEntryPersistence) {

		this.ercVersionedEntryPersistence = ercVersionedEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.compat710.model.ERCVersionedEntry",
			ercVersionedEntryLocalService);

		ERCVersionedEntryLocalServiceUtil.setService(
			ercVersionedEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.compat710.model.ERCVersionedEntry");

		ERCVersionedEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ERCVersionedEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ERCVersionedEntry.class;
	}

	protected String getModelClassName() {
		return ERCVersionedEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = ercVersionedEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = ERCVersionedEntryLocalService.class)
	protected ERCVersionedEntryLocalService ercVersionedEntryLocalService;

	@BeanReference(type = ERCVersionedEntryPersistence.class)
	protected ERCVersionedEntryPersistence ercVersionedEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ERCVersionedEntryLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}
// SB-Hash:-1410784507