##
## Test Suites
##

    modified.files.includes[relevant][antisamy-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=antisamy-java-rule

    test.batch.names[relevant][antisamy-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][antisamy-java-rule]=\
        apps/portal-security/portal-security-antisamy*/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][antisamy-java-rule]=\
        apps/portal-security/portal-security-antisamy*/*Test.java

##
## Testray
##

    testray.main.component.name=AntiSamy