/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.audiences.model.impl;

import com.liferay.audiences.model.AudiencesEntry;
import com.liferay.audiences.model.AudiencesEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AudiencesEntry service. Represents a row in the &quot;AudiencesEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AudiencesEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AudiencesEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AudiencesEntryImpl
 * @generated
 */
@JSON(strict = true)
public class AudiencesEntryModelImpl
	extends BaseModelImpl<AudiencesEntry> implements AudiencesEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audiences entry model instance should use the <code>AudiencesEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "AudiencesEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"externalReferenceCode", Types.VARCHAR},
		{"audiencesEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"json", Types.CLOB}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("audiencesEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("json", Types.CLOB);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AudiencesEntry (mvccVersion LONG default 0 not null,externalReferenceCode VARCHAR(75) null,audiencesEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,json TEXT null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AudiencesEntry";

	public static final String ENTITY_ALIAS = "audiencesEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY audiencesEntry.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AudiencesEntry.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AudiencesEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _audiencesEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAudiencesEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _audiencesEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AudiencesEntry.class;
	}

	@Override
	public String getModelClassName() {
		return AudiencesEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AudiencesEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AudiencesEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AudiencesEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AudiencesEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AudiencesEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AudiencesEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AudiencesEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AudiencesEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AudiencesEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AudiencesEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AudiencesEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AudiencesEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", AudiencesEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				AudiencesEntry::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"audiencesEntryId", AudiencesEntry::getAudiencesEntryId);
			attributeGetterFunctions.put(
				"companyId", AudiencesEntry::getCompanyId);
			attributeGetterFunctions.put("userId", AudiencesEntry::getUserId);
			attributeGetterFunctions.put(
				"userName", AudiencesEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", AudiencesEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AudiencesEntry::getModifiedDate);
			attributeGetterFunctions.put("json", AudiencesEntry::getJSON);
			attributeGetterFunctions.put("name", AudiencesEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AudiencesEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AudiencesEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AudiencesEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<AudiencesEntry, Long>)
					AudiencesEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<AudiencesEntry, String>)
					AudiencesEntry::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"audiencesEntryId",
				(BiConsumer<AudiencesEntry, Long>)
					AudiencesEntry::setAudiencesEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AudiencesEntry, Long>)AudiencesEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AudiencesEntry, Long>)AudiencesEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AudiencesEntry, String>)
					AudiencesEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AudiencesEntry, Date>)
					AudiencesEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AudiencesEntry, Date>)
					AudiencesEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"json",
				(BiConsumer<AudiencesEntry, String>)AudiencesEntry::setJSON);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<AudiencesEntry, String>)AudiencesEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getAudiencesEntryId() {
		return _audiencesEntryId;
	}

	@Override
	public void setAudiencesEntryId(long audiencesEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_audiencesEntryId = audiencesEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getJSON() {
		if (_json == null) {
			return "";
		}
		else {
			return _json;
		}
	}

	@Override
	public void setJSON(String json) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_json = json;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AudiencesEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AudiencesEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AudiencesEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AudiencesEntryImpl audiencesEntryImpl = new AudiencesEntryImpl();

		audiencesEntryImpl.setMvccVersion(getMvccVersion());
		audiencesEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		audiencesEntryImpl.setAudiencesEntryId(getAudiencesEntryId());
		audiencesEntryImpl.setCompanyId(getCompanyId());
		audiencesEntryImpl.setUserId(getUserId());
		audiencesEntryImpl.setUserName(getUserName());
		audiencesEntryImpl.setCreateDate(getCreateDate());
		audiencesEntryImpl.setModifiedDate(getModifiedDate());
		audiencesEntryImpl.setJSON(getJSON());
		audiencesEntryImpl.setName(getName());

		audiencesEntryImpl.resetOriginalValues();

		return audiencesEntryImpl;
	}

	@Override
	public AudiencesEntry cloneWithOriginalValues() {
		AudiencesEntryImpl audiencesEntryImpl = new AudiencesEntryImpl();

		audiencesEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		audiencesEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		audiencesEntryImpl.setAudiencesEntryId(
			this.<Long>getColumnOriginalValue("audiencesEntryId"));
		audiencesEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		audiencesEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		audiencesEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		audiencesEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		audiencesEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		audiencesEntryImpl.setJSON(this.<String>getColumnOriginalValue("json"));
		audiencesEntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return audiencesEntryImpl;
	}

	@Override
	public int compareTo(AudiencesEntry audiencesEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), audiencesEntry.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AudiencesEntry)) {
			return false;
		}

		AudiencesEntry audiencesEntry = (AudiencesEntry)object;

		long primaryKey = audiencesEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AudiencesEntry> toCacheModel() {
		AudiencesEntryCacheModel audiencesEntryCacheModel =
			new AudiencesEntryCacheModel();

		audiencesEntryCacheModel.mvccVersion = getMvccVersion();

		audiencesEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			audiencesEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			audiencesEntryCacheModel.externalReferenceCode = null;
		}

		audiencesEntryCacheModel.audiencesEntryId = getAudiencesEntryId();

		audiencesEntryCacheModel.companyId = getCompanyId();

		audiencesEntryCacheModel.userId = getUserId();

		audiencesEntryCacheModel.userName = getUserName();

		String userName = audiencesEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			audiencesEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			audiencesEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			audiencesEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			audiencesEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			audiencesEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		audiencesEntryCacheModel.json = getJSON();

		String json = audiencesEntryCacheModel.json;

		if ((json != null) && (json.length() == 0)) {
			audiencesEntryCacheModel.json = null;
		}

		audiencesEntryCacheModel.name = getName();

		String name = audiencesEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			audiencesEntryCacheModel.name = null;
		}

		return audiencesEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AudiencesEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AudiencesEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AudiencesEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AudiencesEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AudiencesEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AudiencesEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _externalReferenceCode;
	private long _audiencesEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _json;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<AudiencesEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AudiencesEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("audiencesEntryId", _audiencesEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("json", _json);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("audiencesEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("json", 256L);

		columnBitmasks.put("name", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AudiencesEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-2018850659