modified.files.includes[relevant][audiences-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][audiences-java-rule]=\
    apps/audiences/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][audiences-java-rule]=\
    apps/audiences/**/*Test.java

relevant.rule.names=audiences-java-rule

test.batch.names[relevant][audiences-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Segmentation