/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portlet.asset.service.base;

import com.liferay.asset.kernel.model.AssetVocabularyGroupRel;
import com.liferay.asset.kernel.service.AssetVocabularyGroupRelService;
import com.liferay.asset.kernel.service.AssetVocabularyGroupRelServiceUtil;
import com.liferay.asset.kernel.service.persistence.AssetVocabularyGroupRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset vocabulary group rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.asset.service.impl.AssetVocabularyGroupRelServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.asset.service.impl.AssetVocabularyGroupRelServiceImpl
 * @generated
 */
public abstract class AssetVocabularyGroupRelServiceBaseImpl
	extends BaseServiceImpl
	implements AssetVocabularyGroupRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetVocabularyGroupRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssetVocabularyGroupRelServiceUtil</code>.
	 */

	/**
	 * Returns the asset vocabulary group rel local service.
	 *
	 * @return the asset vocabulary group rel local service
	 */
	public com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalService
		getAssetVocabularyGroupRelLocalService() {

		return assetVocabularyGroupRelLocalService;
	}

	/**
	 * Sets the asset vocabulary group rel local service.
	 *
	 * @param assetVocabularyGroupRelLocalService the asset vocabulary group rel local service
	 */
	public void setAssetVocabularyGroupRelLocalService(
		com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalService
			assetVocabularyGroupRelLocalService) {

		this.assetVocabularyGroupRelLocalService =
			assetVocabularyGroupRelLocalService;
	}

	/**
	 * Returns the asset vocabulary group rel remote service.
	 *
	 * @return the asset vocabulary group rel remote service
	 */
	public AssetVocabularyGroupRelService getAssetVocabularyGroupRelService() {
		return assetVocabularyGroupRelService;
	}

	/**
	 * Sets the asset vocabulary group rel remote service.
	 *
	 * @param assetVocabularyGroupRelService the asset vocabulary group rel remote service
	 */
	public void setAssetVocabularyGroupRelService(
		AssetVocabularyGroupRelService assetVocabularyGroupRelService) {

		this.assetVocabularyGroupRelService = assetVocabularyGroupRelService;
	}

	/**
	 * Returns the asset vocabulary group rel persistence.
	 *
	 * @return the asset vocabulary group rel persistence
	 */
	public AssetVocabularyGroupRelPersistence
		getAssetVocabularyGroupRelPersistence() {

		return assetVocabularyGroupRelPersistence;
	}

	/**
	 * Sets the asset vocabulary group rel persistence.
	 *
	 * @param assetVocabularyGroupRelPersistence the asset vocabulary group rel persistence
	 */
	public void setAssetVocabularyGroupRelPersistence(
		AssetVocabularyGroupRelPersistence assetVocabularyGroupRelPersistence) {

		this.assetVocabularyGroupRelPersistence =
			assetVocabularyGroupRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		AssetVocabularyGroupRelServiceUtil.setService(
			assetVocabularyGroupRelService);
	}

	public void destroy() {
		AssetVocabularyGroupRelServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetVocabularyGroupRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetVocabularyGroupRel.class;
	}

	protected String getModelClassName() {
		return AssetVocabularyGroupRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			assetVocabularyGroupRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalService.class
	)
	protected
		com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalService
			assetVocabularyGroupRelLocalService;

	@BeanReference(type = AssetVocabularyGroupRelService.class)
	protected AssetVocabularyGroupRelService assetVocabularyGroupRelService;

	@BeanReference(type = AssetVocabularyGroupRelPersistence.class)
	protected AssetVocabularyGroupRelPersistence
		assetVocabularyGroupRelPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetVocabularyGroupRelServiceBaseImpl.class);

}
// SB-Hash:2086754013