/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portlet.asset.service.base;

import com.liferay.asset.kernel.model.AssetTagGroupRel;
import com.liferay.asset.kernel.service.AssetTagGroupRelService;
import com.liferay.asset.kernel.service.AssetTagGroupRelServiceUtil;
import com.liferay.asset.kernel.service.persistence.AssetTagGroupRelPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset tag group rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.asset.service.impl.AssetTagGroupRelServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.asset.service.impl.AssetTagGroupRelServiceImpl
 * @generated
 */
public abstract class AssetTagGroupRelServiceBaseImpl
	extends BaseServiceImpl
	implements AssetTagGroupRelService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetTagGroupRelService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssetTagGroupRelServiceUtil</code>.
	 */

	/**
	 * Returns the asset tag group rel local service.
	 *
	 * @return the asset tag group rel local service
	 */
	public com.liferay.asset.kernel.service.AssetTagGroupRelLocalService
		getAssetTagGroupRelLocalService() {

		return assetTagGroupRelLocalService;
	}

	/**
	 * Sets the asset tag group rel local service.
	 *
	 * @param assetTagGroupRelLocalService the asset tag group rel local service
	 */
	public void setAssetTagGroupRelLocalService(
		com.liferay.asset.kernel.service.AssetTagGroupRelLocalService
			assetTagGroupRelLocalService) {

		this.assetTagGroupRelLocalService = assetTagGroupRelLocalService;
	}

	/**
	 * Returns the asset tag group rel remote service.
	 *
	 * @return the asset tag group rel remote service
	 */
	public AssetTagGroupRelService getAssetTagGroupRelService() {
		return assetTagGroupRelService;
	}

	/**
	 * Sets the asset tag group rel remote service.
	 *
	 * @param assetTagGroupRelService the asset tag group rel remote service
	 */
	public void setAssetTagGroupRelService(
		AssetTagGroupRelService assetTagGroupRelService) {

		this.assetTagGroupRelService = assetTagGroupRelService;
	}

	/**
	 * Returns the asset tag group rel persistence.
	 *
	 * @return the asset tag group rel persistence
	 */
	public AssetTagGroupRelPersistence getAssetTagGroupRelPersistence() {
		return assetTagGroupRelPersistence;
	}

	/**
	 * Sets the asset tag group rel persistence.
	 *
	 * @param assetTagGroupRelPersistence the asset tag group rel persistence
	 */
	public void setAssetTagGroupRelPersistence(
		AssetTagGroupRelPersistence assetTagGroupRelPersistence) {

		this.assetTagGroupRelPersistence = assetTagGroupRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		AssetTagGroupRelServiceUtil.setService(assetTagGroupRelService);
	}

	public void destroy() {
		AssetTagGroupRelServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetTagGroupRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetTagGroupRel.class;
	}

	protected String getModelClassName() {
		return AssetTagGroupRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = assetTagGroupRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.asset.kernel.service.AssetTagGroupRelLocalService.class
	)
	protected com.liferay.asset.kernel.service.AssetTagGroupRelLocalService
		assetTagGroupRelLocalService;

	@BeanReference(type = AssetTagGroupRelService.class)
	protected AssetTagGroupRelService assetTagGroupRelService;

	@BeanReference(type = AssetTagGroupRelPersistence.class)
	protected AssetTagGroupRelPersistence assetTagGroupRelPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetTagGroupRelServiceBaseImpl.class);

}
// SB-Hash:176736009