/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portlet.asset.service.base;

import com.liferay.asset.kernel.model.AssetVocabularyGroupRel;
import com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalService;
import com.liferay.asset.kernel.service.AssetVocabularyGroupRelLocalServiceUtil;
import com.liferay.asset.kernel.service.persistence.AssetVocabularyGroupRelPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset vocabulary group rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.asset.service.impl.AssetVocabularyGroupRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.asset.service.impl.AssetVocabularyGroupRelLocalServiceImpl
 * @generated
 */
public abstract class AssetVocabularyGroupRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AssetVocabularyGroupRelLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetVocabularyGroupRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssetVocabularyGroupRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asset vocabulary group rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyGroupRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyGroupRel the asset vocabulary group rel
	 * @return the asset vocabulary group rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetVocabularyGroupRel addAssetVocabularyGroupRel(
		AssetVocabularyGroupRel assetVocabularyGroupRel) {

		assetVocabularyGroupRel.setNew(true);

		return assetVocabularyGroupRelPersistence.update(
			assetVocabularyGroupRel);
	}

	/**
	 * Creates a new asset vocabulary group rel with the primary key. Does not add the asset vocabulary group rel to the database.
	 *
	 * @param assetVocabularyGroupRelId the primary key for the new asset vocabulary group rel
	 * @return the new asset vocabulary group rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetVocabularyGroupRel createAssetVocabularyGroupRel(
		long assetVocabularyGroupRelId) {

		return assetVocabularyGroupRelPersistence.create(
			assetVocabularyGroupRelId);
	}

	/**
	 * Deletes the asset vocabulary group rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyGroupRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyGroupRelId the primary key of the asset vocabulary group rel
	 * @return the asset vocabulary group rel that was removed
	 * @throws PortalException if a asset vocabulary group rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetVocabularyGroupRel deleteAssetVocabularyGroupRel(
			long assetVocabularyGroupRelId)
		throws PortalException {

		return assetVocabularyGroupRelPersistence.remove(
			assetVocabularyGroupRelId);
	}

	/**
	 * Deletes the asset vocabulary group rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyGroupRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyGroupRel the asset vocabulary group rel
	 * @return the asset vocabulary group rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetVocabularyGroupRel deleteAssetVocabularyGroupRel(
		AssetVocabularyGroupRel assetVocabularyGroupRel) {

		return assetVocabularyGroupRelPersistence.remove(
			assetVocabularyGroupRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return assetVocabularyGroupRelPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssetVocabularyGroupRel.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetVocabularyGroupRelPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.asset.model.impl.AssetVocabularyGroupRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assetVocabularyGroupRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.asset.model.impl.AssetVocabularyGroupRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assetVocabularyGroupRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetVocabularyGroupRelPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assetVocabularyGroupRelPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssetVocabularyGroupRel fetchAssetVocabularyGroupRel(
		long assetVocabularyGroupRelId) {

		return assetVocabularyGroupRelPersistence.fetchByPrimaryKey(
			assetVocabularyGroupRelId);
	}

	/**
	 * Returns the asset vocabulary group rel matching the UUID and group.
	 *
	 * @param uuid the asset vocabulary group rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset vocabulary group rel, or <code>null</code> if a matching asset vocabulary group rel could not be found
	 */
	@Override
	public AssetVocabularyGroupRel fetchAssetVocabularyGroupRelByUuidAndGroupId(
		String uuid, long groupId) {

		return assetVocabularyGroupRelPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the asset vocabulary group rel with the primary key.
	 *
	 * @param assetVocabularyGroupRelId the primary key of the asset vocabulary group rel
	 * @return the asset vocabulary group rel
	 * @throws PortalException if a asset vocabulary group rel with the primary key could not be found
	 */
	@Override
	public AssetVocabularyGroupRel getAssetVocabularyGroupRel(
			long assetVocabularyGroupRelId)
		throws PortalException {

		return assetVocabularyGroupRelPersistence.findByPrimaryKey(
			assetVocabularyGroupRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assetVocabularyGroupRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetVocabularyGroupRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyGroupRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assetVocabularyGroupRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AssetVocabularyGroupRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyGroupRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assetVocabularyGroupRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetVocabularyGroupRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyGroupRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetVocabularyGroupRelPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AssetVocabularyGroupRelLocalServiceImpl#deleteAssetVocabularyGroupRel(AssetVocabularyGroupRel) to avoid orphaned data");
		}

		return assetVocabularyGroupRelLocalService.
			deleteAssetVocabularyGroupRel(
				(AssetVocabularyGroupRel)persistedModel);
	}

	@Override
	public BasePersistence<AssetVocabularyGroupRel> getBasePersistence() {
		return assetVocabularyGroupRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetVocabularyGroupRelPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the asset vocabulary group rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset vocabulary group rels
	 * @param companyId the primary key of the company
	 * @return the matching asset vocabulary group rels, or an empty list if no matches were found
	 */
	@Override
	public List<AssetVocabularyGroupRel>
		getAssetVocabularyGroupRelsByUuidAndCompanyId(
			String uuid, long companyId) {

		return assetVocabularyGroupRelPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of asset vocabulary group rels matching the UUID and company.
	 *
	 * @param uuid the UUID of the asset vocabulary group rels
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of asset vocabulary group rels
	 * @param end the upper bound of the range of asset vocabulary group rels (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching asset vocabulary group rels, or an empty list if no matches were found
	 */
	@Override
	public List<AssetVocabularyGroupRel>
		getAssetVocabularyGroupRelsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<AssetVocabularyGroupRel> orderByComparator) {

		return assetVocabularyGroupRelPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the asset vocabulary group rel matching the UUID and group.
	 *
	 * @param uuid the asset vocabulary group rel's UUID
	 * @param groupId the primary key of the group
	 * @return the matching asset vocabulary group rel
	 * @throws PortalException if a matching asset vocabulary group rel could not be found
	 */
	@Override
	public AssetVocabularyGroupRel getAssetVocabularyGroupRelByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return assetVocabularyGroupRelPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the asset vocabulary group rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.asset.model.impl.AssetVocabularyGroupRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset vocabulary group rels
	 * @param end the upper bound of the range of asset vocabulary group rels (not inclusive)
	 * @return the range of asset vocabulary group rels
	 */
	@Override
	public List<AssetVocabularyGroupRel> getAssetVocabularyGroupRels(
		int start, int end) {

		return assetVocabularyGroupRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset vocabulary group rels.
	 *
	 * @return the number of asset vocabulary group rels
	 */
	@Override
	public int getAssetVocabularyGroupRelsCount() {
		return assetVocabularyGroupRelPersistence.countAll();
	}

	/**
	 * Updates the asset vocabulary group rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyGroupRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyGroupRel the asset vocabulary group rel
	 * @return the asset vocabulary group rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetVocabularyGroupRel updateAssetVocabularyGroupRel(
		AssetVocabularyGroupRel assetVocabularyGroupRel) {

		return assetVocabularyGroupRelPersistence.update(
			assetVocabularyGroupRel);
	}

	/**
	 * Returns the asset vocabulary group rel local service.
	 *
	 * @return the asset vocabulary group rel local service
	 */
	public AssetVocabularyGroupRelLocalService
		getAssetVocabularyGroupRelLocalService() {

		return assetVocabularyGroupRelLocalService;
	}

	/**
	 * Sets the asset vocabulary group rel local service.
	 *
	 * @param assetVocabularyGroupRelLocalService the asset vocabulary group rel local service
	 */
	public void setAssetVocabularyGroupRelLocalService(
		AssetVocabularyGroupRelLocalService
			assetVocabularyGroupRelLocalService) {

		this.assetVocabularyGroupRelLocalService =
			assetVocabularyGroupRelLocalService;
	}

	/**
	 * Returns the asset vocabulary group rel persistence.
	 *
	 * @return the asset vocabulary group rel persistence
	 */
	public AssetVocabularyGroupRelPersistence
		getAssetVocabularyGroupRelPersistence() {

		return assetVocabularyGroupRelPersistence;
	}

	/**
	 * Sets the asset vocabulary group rel persistence.
	 *
	 * @param assetVocabularyGroupRelPersistence the asset vocabulary group rel persistence
	 */
	public void setAssetVocabularyGroupRelPersistence(
		AssetVocabularyGroupRelPersistence assetVocabularyGroupRelPersistence) {

		this.assetVocabularyGroupRelPersistence =
			assetVocabularyGroupRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		AssetVocabularyGroupRelLocalServiceUtil.setService(
			assetVocabularyGroupRelLocalService);
	}

	public void destroy() {
		AssetVocabularyGroupRelLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetVocabularyGroupRelLocalService.class.getName();
	}

	@Override
	public CTPersistence<AssetVocabularyGroupRel> getCTPersistence() {
		return assetVocabularyGroupRelPersistence;
	}

	@Override
	public Class<AssetVocabularyGroupRel> getModelClass() {
		return AssetVocabularyGroupRel.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<AssetVocabularyGroupRel>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(assetVocabularyGroupRelPersistence);
	}

	protected String getModelClassName() {
		return AssetVocabularyGroupRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			assetVocabularyGroupRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = AssetVocabularyGroupRelLocalService.class)
	protected AssetVocabularyGroupRelLocalService
		assetVocabularyGroupRelLocalService;

	@BeanReference(type = AssetVocabularyGroupRelPersistence.class)
	protected AssetVocabularyGroupRelPersistence
		assetVocabularyGroupRelPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetVocabularyGroupRelLocalServiceBaseImpl.class);

}
// SB-Hash:-1067315460