#
# This is a generated file.
#

api.version=v1.0
crud.entity.class.name=com.liferay.headless.digital.sales.room.dto.v1_0.DigitalSalesRoomTemplate
crud.item.delegate=true
entity.class.name=com.liferay.headless.digital.sales.room.dto.v1_0.DigitalSalesRoomTemplate
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Digital.Sales.Room)
osgi.jaxrs.resource=true