argo:
    workflowSpec:
        artifactGC:
            strategy: OnWorkflowDeletion
        podGC:
            strategy: OnWorkflowSuccess
        ttlStrategy:
            secondsAfterCompletion: 86400