apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/sync-wave: "-60"
    name: liferayinfrastructures.aws.liferay.com
spec:
    group: aws.liferay.com
    names:
        kind: LiferayInfrastructure
        plural: liferayinfrastructures
        shortNames:
            -   lfrinfra
            -   lri
        singular: liferayinfrastructure
    versions:
        -   name: v1alpha1
            referenceable: true
            schema:
                openAPIV3Schema:
                    properties:
                        spec:
                            properties:
                                activeDataPlane:
                                    default: blue
                                    enum:
                                        -   blue
                                        -   green
                                    type: string
                                backup:
                                    properties:
                                        enabled:
                                            default: false
                                            type: boolean
                                        region:
                                            type: string
                                        rules:
                                            items:
                                                properties:
                                                    retentionDays:
                                                        type: integer
                                                    ruleName:
                                                        type: string
                                                    schedule:
                                                        type: string
                                                    startWindow:
                                                        type: integer
                                                required:
                                                    -   retentionDays
                                                    -   ruleName
                                                    -   schedule
                                                    -   startWindow
                                                type: object
                                            minItems: 1
                                            type: array
                                    required:
                                        -   region
                                        -   rules
                                    type: object
                                commonTags:
                                    additionalProperties: true
                                    default: {}
                                    type: object
                                database:
                                    properties:
                                        engineVersion:
                                            default: "16.11"
                                            type: string
                                        instanceClass:
                                            default: db.t3.medium
                                            type: string
                                        isRestoring:
                                            default: false
                                            type: boolean
                                        region:
                                            default: us-west-2
                                            type: string
                                        snapshotIdentifier:
                                            type: string
                                        storageGB:
                                            default: 20
                                            type: integer
                                        username:
                                            default: liferay_database_admin
                                            type: string
                                    required:
                                        -   region
                                    type: object
                                deletionProtection:
                                    default: false
                                    type: boolean
                                environmentId:
                                    type: string
                                overlay:
                                    properties:
                                        region:
                                            default: us-west-2
                                            type: string
                                    required:
                                        -   region
                                    type: object
                                projectId:
                                    type: string
                                search:
                                    properties:
                                        engineVersion:
                                            default: OpenSearch_2.15
                                            type: string
                                        instanceCount:
                                            default: 2
                                            type: integer
                                        instanceType:
                                            default: t3.small.search
                                            type: string
                                        region:
                                            default: us-west-2
                                            type: string
                                        username:
                                            default: liferay_search_admin
                                            type: string
                                    required:
                                        -   region
                                    type: object
                                storage:
                                    properties:
                                        region:
                                            default: us-west-2
                                            type: string
                                    required:
                                        -   region
                                    type: object
                            required:
                                -   database
                                -   deletionProtection
                                -   environmentId
                                -   projectId
                                -   search
                                -   storage
                            type: object
                    type: object
            served: true