before_cache:
    -   rm -f  .gradle/caches/modules-2/modules-2.lock
    -   rm -fr .gradle/caches/*/plugin-resolution/
before_install:
    -   wget http://github.com/liferay/liferay-binaries-cache-2020/raw/master/gradle-6.6.1.LIFERAY-PATCHED-1-bin.zip
    -   unzip -qq gradle-6.6.1.LIFERAY-PATCHED-1-bin.zip
    -   export GRADLE_HOME=${PWD}/gradle-6.6.1
    -   export PATH=${GRADLE_HOME}/bin:${PATH}
    -   gradle wrapper
cache:
    directories:
        -   .gradle/caches/
        -   .gradle/wrapper/
    timeout: 600
dist: bionic
env:
    global:
        -   NODE_OPTIONS=--max_old_space_size=2048
jdk: openjdk8
jobs:
    include:
        -   name: "Analysis"
            script: ./gradlew checkSourceFormatting packageRunLint pmdMain pmdTest pmdTestIntegration spotbugsMain spotbugsTest spotbugsTestIntegration --configure-on-demand --continue --parallel
        -   name: "Tests"
            after_success:
                -   test ${TRAVIS_BRANCH} = "7.1.x" &&
                    test ${TRAVIS_EVENT_TYPE} = "push" &&
                    test ${TRAVIS_REPO_SLUG} = "liferay/com-liferay-osb-faro-private" &&
                    ./gradlew packageRunCoveralls --no-daemon && ./gradlew pushAppDockerImage -Pdocker.image.tag=master --no-daemon
                -   test ${TRAVIS_BRANCH} = "3.1.x" &&
                    test ${TRAVIS_EVENT_TYPE} = "push" &&
                    test ${TRAVIS_REPO_SLUG} = "liferay/com-liferay-osb-faro-private" &&
                    ./gradlew packageRunCoveralls --no-daemon && ./gradlew pushAppDockerImage -Pdocker.image.tag=release --no-daemon
            script: ./gradlew packageRunWebpack packageRunTest test --no-daemon
language: java
os: linux
services:
    -   docker