##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        **/buildSrc/**,\
        **/gradle/wrapper/gradle-wrapper.properties,\
        **/osb-faro-login-web-fragment/**,\
        **/osb-faro-service/src/main/resources/com/liferay/osb/faro/dependencies/**,\
        **/osb-faro-web/src/main/resources/META-INF/resources/dist/**

##
## Git
##

    git.liferay.portal.branch=master

##
## Source Check Properties
##

    source.check.BNDIncludeResourceCheck.checkTestIncludeResource=false

    source.check.JavaExceptionCheck.enabled=false

    source.check.JSONDeprecatedPackagesCheck.enabled=false

    source.check.PropertiesLanguageKeysCheck.enabled=false