#
# Application
#

liferay.hubspot.token=${LIFERAY_HUBSPOT_TOKEN}
liferay.hubspot.url=${LIFERAY_HUBSPOT_URL:https://api.hubapi.com}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-hubspot-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_HUBSPOT_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-hubspot-etc-spring-boot-oahs,\
    liferay-hubspot-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081