/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.model.impl;

import com.liferay.object.model.ObjectView;
import com.liferay.object.service.ObjectViewLocalServiceUtil;

/**
 * The extended model base implementation for the ObjectView service. Represents a row in the &quot;ObjectView&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectViewImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ObjectViewImpl
 * @see ObjectView
 * @generated
 */
public abstract class ObjectViewBaseImpl
	extends ObjectViewModelImpl implements ObjectView {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a object view model instance should use the <code>ObjectView</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ObjectViewLocalServiceUtil.addObjectView(this);
		}
		else {
			ObjectViewLocalServiceUtil.updateObjectView(this);
		}
	}

}
// SB-Hash:817655519