/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.model.impl;

import com.liferay.object.model.ObjectViewSortColumn;

/**
 * The extended model base implementation for the ObjectViewSortColumn service. Represents a row in the &quot;ObjectViewSortColumn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObjectViewSortColumnImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ObjectViewSortColumnImpl
 * @see ObjectViewSortColumn
 * @generated
 */
public abstract class ObjectViewSortColumnBaseImpl
	extends ObjectViewSortColumnModelImpl implements ObjectViewSortColumn {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a object view sort column model instance should use the <code>ObjectViewSortColumn</code> interface instead.
	 */

}
// SB-Hash:1799956969