/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.inventory.model.impl;

import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseRel;
import com.liferay.commerce.inventory.service.CommerceInventoryWarehouseRelLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceInventoryWarehouseRel service. Represents a row in the &quot;CIWarehouseRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceInventoryWarehouseRelImpl}.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceInventoryWarehouseRelImpl
 * @see CommerceInventoryWarehouseRel
 * @generated
 */
public abstract class CommerceInventoryWarehouseRelBaseImpl
	extends CommerceInventoryWarehouseRelModelImpl
	implements CommerceInventoryWarehouseRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce inventory warehouse rel model instance should use the <code>CommerceInventoryWarehouseRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceInventoryWarehouseRelLocalServiceUtil.
				addCommerceInventoryWarehouseRel(this);
		}
		else {
			CommerceInventoryWarehouseRelLocalServiceUtil.
				updateCommerceInventoryWarehouseRel(this);
		}
	}

}
// SB-Hash:-1176384860