/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.cookies.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CookiesConsentPreference service. Represents a row in the &quot;CookiesConsentPreference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.cookies.model.impl.CookiesConsentPreferenceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.cookies.model.impl.CookiesConsentPreferenceImpl</code>.
 * </p>
 *
 * @author Christopher Kian
 * @see CookiesConsentPreference
 * @generated
 */
@ProviderType
public interface CookiesConsentPreferenceModel
	extends BaseModel<CookiesConsentPreference>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cookies consent preference model instance should use the {@link CookiesConsentPreference} interface instead.
	 */

	/**
	 * Returns the primary key of this cookies consent preference.
	 *
	 * @return the primary key of this cookies consent preference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cookies consent preference.
	 *
	 * @param primaryKey the primary key of this cookies consent preference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this cookies consent preference.
	 *
	 * @return the mvcc version of this cookies consent preference
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this cookies consent preference.
	 *
	 * @param mvccVersion the mvcc version of this cookies consent preference
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the cookies consent preference ID of this cookies consent preference.
	 *
	 * @return the cookies consent preference ID of this cookies consent preference
	 */
	public long getCookiesConsentPreferenceId();

	/**
	 * Sets the cookies consent preference ID of this cookies consent preference.
	 *
	 * @param cookiesConsentPreferenceId the cookies consent preference ID of this cookies consent preference
	 */
	public void setCookiesConsentPreferenceId(long cookiesConsentPreferenceId);

	/**
	 * Returns the company ID of this cookies consent preference.
	 *
	 * @return the company ID of this cookies consent preference
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cookies consent preference.
	 *
	 * @param companyId the company ID of this cookies consent preference
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cookies consent preference.
	 *
	 * @return the user ID of this cookies consent preference
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cookies consent preference.
	 *
	 * @param userId the user ID of this cookies consent preference
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cookies consent preference.
	 *
	 * @return the user uuid of this cookies consent preference
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cookies consent preference.
	 *
	 * @param userUuid the user uuid of this cookies consent preference
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cookies consent preference.
	 *
	 * @return the user name of this cookies consent preference
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this cookies consent preference.
	 *
	 * @param userName the user name of this cookies consent preference
	 */
	public void setUserName(String userName);

	/**
	 * Returns the domain of this cookies consent preference.
	 *
	 * @return the domain of this cookies consent preference
	 */
	@AutoEscape
	public String getDomain();

	/**
	 * Sets the domain of this cookies consent preference.
	 *
	 * @param domain the domain of this cookies consent preference
	 */
	public void setDomain(String domain);

	/**
	 * Returns the expiration date of this cookies consent preference.
	 *
	 * @return the expiration date of this cookies consent preference
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this cookies consent preference.
	 *
	 * @param expirationDate the expiration date of this cookies consent preference
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the name of this cookies consent preference.
	 *
	 * @return the name of this cookies consent preference
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cookies consent preference.
	 *
	 * @param name the name of this cookies consent preference
	 */
	public void setName(String name);

	/**
	 * Returns the value of this cookies consent preference.
	 *
	 * @return the value of this cookies consent preference
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this cookies consent preference.
	 *
	 * @param value the value of this cookies consent preference
	 */
	public void setValue(String value);

	@Override
	public CookiesConsentPreference cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1412906055