/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat720.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.compat720.model.BasicEntry;
import com.liferay.portal.tools.service.builder.test.compat720.service.BasicEntryLocalService;
import com.liferay.portal.tools.service.builder.test.compat720.service.BasicEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.compat720.service.persistence.BasicEntryPersistence;
import com.liferay.portal.tools.service.builder.test.compat720.service.persistence.MappingEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the basic entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.compat720.service.impl.BasicEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.compat720.service.impl.BasicEntryLocalServiceImpl
 * @generated
 */
public abstract class BasicEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements BasicEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BasicEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>BasicEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the basic entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BasicEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param basicEntry the basic entry
	 * @return the basic entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BasicEntry addBasicEntry(BasicEntry basicEntry) {
		basicEntry.setNew(true);

		return basicEntryPersistence.update(basicEntry);
	}

	/**
	 * Creates a new basic entry with the primary key. Does not add the basic entry to the database.
	 *
	 * @param basicEntryId the primary key for the new basic entry
	 * @return the new basic entry
	 */
	@Override
	@Transactional(enabled = false)
	public BasicEntry createBasicEntry(long basicEntryId) {
		return basicEntryPersistence.create(basicEntryId);
	}

	/**
	 * Deletes the basic entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BasicEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param basicEntryId the primary key of the basic entry
	 * @return the basic entry that was removed
	 * @throws PortalException if a basic entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BasicEntry deleteBasicEntry(long basicEntryId)
		throws PortalException {

		return basicEntryPersistence.remove(basicEntryId);
	}

	/**
	 * Deletes the basic entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BasicEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param basicEntry the basic entry
	 * @return the basic entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BasicEntry deleteBasicEntry(BasicEntry basicEntry) {
		return basicEntryPersistence.remove(basicEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BasicEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return basicEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat720.model.impl.BasicEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return basicEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat720.model.impl.BasicEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return basicEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return basicEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return basicEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BasicEntry fetchBasicEntry(long basicEntryId) {
		return basicEntryPersistence.fetchByPrimaryKey(basicEntryId);
	}

	/**
	 * Returns the basic entry with the primary key.
	 *
	 * @param basicEntryId the primary key of the basic entry
	 * @return the basic entry
	 * @throws PortalException if a basic entry with the primary key could not be found
	 */
	@Override
	public BasicEntry getBasicEntry(long basicEntryId) throws PortalException {
		return basicEntryPersistence.findByPrimaryKey(basicEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(basicEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BasicEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("basicEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			basicEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BasicEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"basicEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(basicEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BasicEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("basicEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return basicEntryLocalService.deleteBasicEntry(
			(BasicEntry)persistedModel);
	}

	public BasePersistence<BasicEntry> getBasePersistence() {
		return basicEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return basicEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the basic entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.compat720.model.impl.BasicEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of basic entries
	 * @param end the upper bound of the range of basic entries (not inclusive)
	 * @return the range of basic entries
	 */
	@Override
	public List<BasicEntry> getBasicEntries(int start, int end) {
		return basicEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of basic entries.
	 *
	 * @return the number of basic entries
	 */
	@Override
	public int getBasicEntriesCount() {
		return basicEntryPersistence.countAll();
	}

	/**
	 * Updates the basic entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BasicEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param basicEntry the basic entry
	 * @return the basic entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BasicEntry updateBasicEntry(BasicEntry basicEntry) {
		return basicEntryPersistence.update(basicEntry);
	}

	/**
	 */
	@Override
	public void addMappingEntryBasicEntry(
		long mappingEntryId, long basicEntryId) {

		mappingEntryPersistence.addBasicEntry(mappingEntryId, basicEntryId);
	}

	/**
	 */
	@Override
	public void addMappingEntryBasicEntry(
		long mappingEntryId, BasicEntry basicEntry) {

		mappingEntryPersistence.addBasicEntry(mappingEntryId, basicEntry);
	}

	/**
	 */
	@Override
	public void addMappingEntryBasicEntries(
		long mappingEntryId, long[] basicEntryIds) {

		mappingEntryPersistence.addBasicEntries(mappingEntryId, basicEntryIds);
	}

	/**
	 */
	@Override
	public void addMappingEntryBasicEntries(
		long mappingEntryId, List<BasicEntry> basicEntries) {

		mappingEntryPersistence.addBasicEntries(mappingEntryId, basicEntries);
	}

	/**
	 */
	@Override
	public void clearMappingEntryBasicEntries(long mappingEntryId) {
		mappingEntryPersistence.clearBasicEntries(mappingEntryId);
	}

	/**
	 */
	@Override
	public void deleteMappingEntryBasicEntry(
		long mappingEntryId, long basicEntryId) {

		mappingEntryPersistence.removeBasicEntry(mappingEntryId, basicEntryId);
	}

	/**
	 */
	@Override
	public void deleteMappingEntryBasicEntry(
		long mappingEntryId, BasicEntry basicEntry) {

		mappingEntryPersistence.removeBasicEntry(mappingEntryId, basicEntry);
	}

	/**
	 */
	@Override
	public void deleteMappingEntryBasicEntries(
		long mappingEntryId, long[] basicEntryIds) {

		mappingEntryPersistence.removeBasicEntries(
			mappingEntryId, basicEntryIds);
	}

	/**
	 */
	@Override
	public void deleteMappingEntryBasicEntries(
		long mappingEntryId, List<BasicEntry> basicEntries) {

		mappingEntryPersistence.removeBasicEntries(
			mappingEntryId, basicEntries);
	}

	/**
	 * Returns the mappingEntryIds of the mapping entries associated with the basic entry.
	 *
	 * @param basicEntryId the basicEntryId of the basic entry
	 * @return long[] the mappingEntryIds of mapping entries associated with the basic entry
	 */
	@Override
	public long[] getMappingEntryPrimaryKeys(long basicEntryId) {
		return basicEntryPersistence.getMappingEntryPrimaryKeys(basicEntryId);
	}

	/**
	 */
	@Override
	public List<BasicEntry> getMappingEntryBasicEntries(long mappingEntryId) {
		return mappingEntryPersistence.getBasicEntries(mappingEntryId);
	}

	/**
	 */
	@Override
	public List<BasicEntry> getMappingEntryBasicEntries(
		long mappingEntryId, int start, int end) {

		return mappingEntryPersistence.getBasicEntries(
			mappingEntryId, start, end);
	}

	/**
	 */
	@Override
	public List<BasicEntry> getMappingEntryBasicEntries(
		long mappingEntryId, int start, int end,
		OrderByComparator<BasicEntry> orderByComparator) {

		return mappingEntryPersistence.getBasicEntries(
			mappingEntryId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getMappingEntryBasicEntriesCount(long mappingEntryId) {
		return mappingEntryPersistence.getBasicEntriesSize(mappingEntryId);
	}

	/**
	 */
	@Override
	public boolean hasMappingEntryBasicEntry(
		long mappingEntryId, long basicEntryId) {

		return mappingEntryPersistence.containsBasicEntry(
			mappingEntryId, basicEntryId);
	}

	/**
	 */
	@Override
	public boolean hasMappingEntryBasicEntries(long mappingEntryId) {
		return mappingEntryPersistence.containsBasicEntries(mappingEntryId);
	}

	/**
	 */
	@Override
	public void setMappingEntryBasicEntries(
		long mappingEntryId, long[] basicEntryIds) {

		mappingEntryPersistence.setBasicEntries(mappingEntryId, basicEntryIds);
	}

	/**
	 * Returns the basic entry local service.
	 *
	 * @return the basic entry local service
	 */
	public BasicEntryLocalService getBasicEntryLocalService() {
		return basicEntryLocalService;
	}

	/**
	 * Sets the basic entry local service.
	 *
	 * @param basicEntryLocalService the basic entry local service
	 */
	public void setBasicEntryLocalService(
		BasicEntryLocalService basicEntryLocalService) {

		this.basicEntryLocalService = basicEntryLocalService;
	}

	/**
	 * Returns the basic entry persistence.
	 *
	 * @return the basic entry persistence
	 */
	public BasicEntryPersistence getBasicEntryPersistence() {
		return basicEntryPersistence;
	}

	/**
	 * Sets the basic entry persistence.
	 *
	 * @param basicEntryPersistence the basic entry persistence
	 */
	public void setBasicEntryPersistence(
		BasicEntryPersistence basicEntryPersistence) {

		this.basicEntryPersistence = basicEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.compat720.model.BasicEntry",
			basicEntryLocalService);

		BasicEntryLocalServiceUtil.setService(basicEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.compat720.model.BasicEntry");

		BasicEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BasicEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BasicEntry.class;
	}

	protected String getModelClassName() {
		return BasicEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = basicEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = BasicEntryLocalService.class)
	protected BasicEntryLocalService basicEntryLocalService;

	@BeanReference(type = BasicEntryPersistence.class)
	protected BasicEntryPersistence basicEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@BeanReference(type = MappingEntryPersistence.class)
	protected MappingEntryPersistence mappingEntryPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		BasicEntryLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}
// SB-Hash:-67836625