{{- if and .Values.global.awsmpServiceAccount.name .Values.global.awsmpServiceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        eks.amazonaws.com/role-arn: {{ .Values.global.awsmpServiceAccount.roleArn }}
    name: {{ .Values.global.awsmpServiceAccount.prefix | default "" }}{{ .Values.global.awsmpServiceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}