compact: true
directory:
    -   .
download-external-modules: true
framework:
    -   helm
    -   kubernetes
    -   secrets
    -   terraform
quiet: true
skip-check:
    -   CKV_GCP_12
    -   CKV_GCP_42
    -   CKV_GCP_69
soft-fail: false