/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat720.model.impl;

import com.liferay.portal.tools.service.builder.test.compat720.model.MVCCEntry;
import com.liferay.portal.tools.service.builder.test.compat720.service.MVCCEntryLocalServiceUtil;

/**
 * The extended model base implementation for the MVCCEntry service. Represents a row in the &quot;MVCCEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MVCCEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MVCCEntryImpl
 * @see MVCCEntry
 * @generated
 */
public abstract class MVCCEntryBaseImpl
	extends MVCCEntryModelImpl implements MVCCEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mvcc entry model instance should use the <code>MVCCEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MVCCEntryLocalServiceUtil.addMVCCEntry(this);
		}
		else {
			MVCCEntryLocalServiceUtil.updateMVCCEntry(this);
		}
	}

}
// SB-Hash:49953564