/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.seo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LayoutSEOEntryCustomMetaTag service. Represents a row in the &quot;LayoutSEOEntryCustomMetaTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.layout.seo.model.impl.LayoutSEOEntryCustomMetaTagModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.layout.seo.model.impl.LayoutSEOEntryCustomMetaTagImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutSEOEntryCustomMetaTag
 * @generated
 */
@ProviderType
public interface LayoutSEOEntryCustomMetaTagModel
	extends BaseModel<LayoutSEOEntryCustomMetaTag>,
			CTModel<LayoutSEOEntryCustomMetaTag>, LocalizedModel, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout seo entry custom meta tag model instance should use the {@link LayoutSEOEntryCustomMetaTag} interface instead.
	 */

	/**
	 * Returns the primary key of this layout seo entry custom meta tag.
	 *
	 * @return the primary key of this layout seo entry custom meta tag
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout seo entry custom meta tag.
	 *
	 * @param primaryKey the primary key of this layout seo entry custom meta tag
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this layout seo entry custom meta tag.
	 *
	 * @return the mvcc version of this layout seo entry custom meta tag
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this layout seo entry custom meta tag.
	 *
	 * @param mvccVersion the mvcc version of this layout seo entry custom meta tag
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this layout seo entry custom meta tag.
	 *
	 * @return the ct collection ID of this layout seo entry custom meta tag
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this layout seo entry custom meta tag.
	 *
	 * @param ctCollectionId the ct collection ID of this layout seo entry custom meta tag
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the layout seo entry custom meta tag ID of this layout seo entry custom meta tag.
	 *
	 * @return the layout seo entry custom meta tag ID of this layout seo entry custom meta tag
	 */
	public long getLayoutSEOEntryCustomMetaTagId();

	/**
	 * Sets the layout seo entry custom meta tag ID of this layout seo entry custom meta tag.
	 *
	 * @param layoutSEOEntryCustomMetaTagId the layout seo entry custom meta tag ID of this layout seo entry custom meta tag
	 */
	public void setLayoutSEOEntryCustomMetaTagId(
		long layoutSEOEntryCustomMetaTagId);

	/**
	 * Returns the group ID of this layout seo entry custom meta tag.
	 *
	 * @return the group ID of this layout seo entry custom meta tag
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this layout seo entry custom meta tag.
	 *
	 * @param groupId the group ID of this layout seo entry custom meta tag
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout seo entry custom meta tag.
	 *
	 * @return the company ID of this layout seo entry custom meta tag
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout seo entry custom meta tag.
	 *
	 * @param companyId the company ID of this layout seo entry custom meta tag
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the layout seo entry ID of this layout seo entry custom meta tag.
	 *
	 * @return the layout seo entry ID of this layout seo entry custom meta tag
	 */
	public long getLayoutSEOEntryId();

	/**
	 * Sets the layout seo entry ID of this layout seo entry custom meta tag.
	 *
	 * @param layoutSEOEntryId the layout seo entry ID of this layout seo entry custom meta tag
	 */
	public void setLayoutSEOEntryId(long layoutSEOEntryId);

	/**
	 * Returns the content of this layout seo entry custom meta tag.
	 *
	 * @return the content of this layout seo entry custom meta tag
	 */
	public String getContent();

	/**
	 * Returns the localized content of this layout seo entry custom meta tag in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized content of this layout seo entry custom meta tag
	 */
	@AutoEscape
	public String getContent(Locale locale);

	/**
	 * Returns the localized content of this layout seo entry custom meta tag in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized content of this layout seo entry custom meta tag. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getContent(Locale locale, boolean useDefault);

	/**
	 * Returns the localized content of this layout seo entry custom meta tag in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized content of this layout seo entry custom meta tag
	 */
	@AutoEscape
	public String getContent(String languageId);

	/**
	 * Returns the localized content of this layout seo entry custom meta tag in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized content of this layout seo entry custom meta tag
	 */
	@AutoEscape
	public String getContent(String languageId, boolean useDefault);

	@AutoEscape
	public String getContentCurrentLanguageId();

	@AutoEscape
	public String getContentCurrentValue();

	/**
	 * Returns a map of the locales and localized contents of this layout seo entry custom meta tag.
	 *
	 * @return the locales and localized contents of this layout seo entry custom meta tag
	 */
	public Map<Locale, String> getContentMap();

	/**
	 * Sets the content of this layout seo entry custom meta tag.
	 *
	 * @param content the content of this layout seo entry custom meta tag
	 */
	public void setContent(String content);

	/**
	 * Sets the localized content of this layout seo entry custom meta tag in the language.
	 *
	 * @param content the localized content of this layout seo entry custom meta tag
	 * @param locale the locale of the language
	 */
	public void setContent(String content, Locale locale);

	/**
	 * Sets the localized content of this layout seo entry custom meta tag in the language, and sets the default locale.
	 *
	 * @param content the localized content of this layout seo entry custom meta tag
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setContent(String content, Locale locale, Locale defaultLocale);

	public void setContentCurrentLanguageId(String languageId);

	/**
	 * Sets the localized contents of this layout seo entry custom meta tag from the map of locales and localized contents.
	 *
	 * @param contentMap the locales and localized contents of this layout seo entry custom meta tag
	 */
	public void setContentMap(Map<Locale, String> contentMap);

	/**
	 * Sets the localized contents of this layout seo entry custom meta tag from the map of locales and localized contents, and sets the default locale.
	 *
	 * @param contentMap the locales and localized contents of this layout seo entry custom meta tag
	 * @param defaultLocale the default locale
	 */
	public void setContentMap(
		Map<Locale, String> contentMap, Locale defaultLocale);

	/**
	 * Returns the property of this layout seo entry custom meta tag.
	 *
	 * @return the property of this layout seo entry custom meta tag
	 */
	@AutoEscape
	public String getProperty();

	/**
	 * Sets the property of this layout seo entry custom meta tag.
	 *
	 * @param property the property of this layout seo entry custom meta tag
	 */
	public void setProperty(String property);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public LayoutSEOEntryCustomMetaTag cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// SB-Hash:732021952