##
## Test Suites
##

    modified.files.includes[relevant][portal-language-rule]=**
    relevant.rule.names=portal-language-rule

    test.batch.names[relevant][portal-language-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-language-rule]=\
        apps/portal-language/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-language-rule]=\
        apps/portal-language/**/*Test.java

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant]=\
        portal-language-override-web

##
## Testray
##

    testray.main.component.name=Language Override