/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.portal.tools.service.builder.test.compat710.model.ERCVersionedEntry;
import com.liferay.portal.tools.service.builder.test.compat710.service.ERCVersionedEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ERCVersionedEntry service. Represents a row in the &quot;ERCVersionedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ERCVersionedEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ERCVersionedEntryImpl
 * @see ERCVersionedEntry
 * @generated
 */
public abstract class ERCVersionedEntryBaseImpl
	extends ERCVersionedEntryModelImpl implements ERCVersionedEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a erc versioned entry model instance should use the <code>ERCVersionedEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ERCVersionedEntryLocalServiceUtil.addERCVersionedEntry(this);
		}
		else {
			ERCVersionedEntryLocalServiceUtil.updateERCVersionedEntry(this);
		}
	}

}
// SB-Hash:-487443640