apiVersion: v1
data:
    {{- if not .Values.configmap.overrideDefaults }}
    000_jdk_java_options.sh: |
        #!/usr/bin/env bash

        export JDK_JAVA_OPTIONS="${JDK_JAVA_OPTIONS} --add-opens=jdk.naming.dns/com.sun.jndi.dns=java.naming"
    com.liferay.portal.k8s.agent.configuration.PortalK8sAgentConfiguration.config: |
        apiServerHost="$[env:KUBERNETES_SERVICE_HOST]"
        apiServerPort="$[env:KUBERNETES_SERVICE_PORT]"
        apiServerSSL=b"true"
        caCertData="$[secret:ca.crt]"
        namespace="$[secret:namespace]"
        saToken="$[secret:token]"
    portal-cloud.properties: |
        {{- if .Values.portalProperties }}
        {{- .Values.portalProperties | nindent 8 }}
        {{- end }}
        {{- range $i := .Values.dependencies }}
        {{- if $i.portalProperties }}
        {{- $i.portalProperties | nindent 8 }}
        {{- end }}
        {{- end }}
        configuration.override.com.liferay.portal.bundle.blacklist.internal.configuration.BundleBlacklistConfiguration_blacklistBundleSymbolicNames=[\
            {{- $PREFIX := "" }}
            {{- range $bundle := .Values.portalBundleDenyList }}
            {{ $PREFIX }}{{ $bundle | quote }}\
            {{- $PREFIX = "," -}}
            {{- end }}
            {{- range $i := .Values.dependencies }}
            {{- range $bundle := $i.portalBundleDenyList }}
            {{ $PREFIX }}{{ $bundle | quote }}\
            {{- $PREFIX = "," -}}
            {{- end }}
            {{- end }}
        ]
        configuration.override.com.liferay.portal.component.blacklist.internal.configuration.ComponentBlacklistConfiguration_blacklistComponentNames=[\
            {{- $PREFIX := "" }}
            {{- range $component := .Values.portalComponentDenyList }}
            {{ $PREFIX }}{{ $component | quote }}\
            {{- $PREFIX = "," }}
            {{- end }}
            {{- range $i := .Values.dependencies }}
            {{- range $component := $i.portalComponentDenyList }}
            {{ $PREFIX }}{{ $component | quote }}\
            {{- $PREFIX = "," }}
            {{- end }}
            {{- end }}
        ]
        {{ if or (gt (int .Values.replicaCount) 1) .Values.autoscaling.enabled -}}
        cluster.link.autodetect.address=
        cluster.link.channel.properties.control=/opt/liferay/unicast.xml
        cluster.link.channel.properties.transport.0=/opt/liferay/unicast.xml
        cluster.link.enabled=true
        enterprise.product.notification.enabled=false
        portlet.session.replicate.enabled=true
        {{ end }}
        {{- tpl (.Files.Get "resources/portal-cloud.properties") $ | nindent 8 }}
    portal-ext.properties: |
        include-and-override=portal-liferay-online-config.properties
        include-and-override=portal-cloud.properties
    {{ if or (gt (int .Values.replicaCount) 1) .Values.autoscaling.enabled }}
    unicast.xml: |
        {{- tpl (.Files.Get "resources/unicast.xml") . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.configmap.data }}
    {{- toYaml .Values.configmap.data | nindent 4 }}
    {{- end }}
kind: ConfigMap
metadata:
    {{- with .Values.configmap.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}