/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.RenameFinderColumnEntry;
import com.liferay.portal.tools.service.builder.test.service.RenameFinderColumnEntryLocalServiceUtil;

/**
 * The extended model base implementation for the RenameFinderColumnEntry service. Represents a row in the &quot;RenameFinderColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RenameFinderColumnEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RenameFinderColumnEntryImpl
 * @see RenameFinderColumnEntry
 * @generated
 */
public abstract class RenameFinderColumnEntryBaseImpl
	extends RenameFinderColumnEntryModelImpl
	implements RenameFinderColumnEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rename finder column entry model instance should use the <code>RenameFinderColumnEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RenameFinderColumnEntryLocalServiceUtil.addRenameFinderColumnEntry(
				this);
		}
		else {
			RenameFinderColumnEntryLocalServiceUtil.
				updateRenameFinderColumnEntry(this);
		}
	}

}
// SB-Hash:451718008