resource "helm_release" "external_secrets" {
	chart="external-secrets"
	create_namespace=true
	name="external-secrets"
	namespace=var.external_secrets_namespace
	repository="https://charts.external-secrets.io"
	values=[
		yamlencode(
			{
				certController={
					podAnnotations=local.karpenter_pod_annotations
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				installCRDs=true
				podAnnotations=local.karpenter_pod_annotations
				resources={
					limits={
						memory="512Mi"
					}
					requests={
						cpu="15m"
						memory="128Mi"
					}
				}
				webhook={
					podAnnotations=local.karpenter_pod_annotations
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
			}),
	]
	version=var.external_secrets_helm_chart_version
	wait=true
}