/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.discount.model.impl;

import com.liferay.commerce.discount.model.CommerceDiscountOrderTypeRel;
import com.liferay.commerce.discount.service.CommerceDiscountOrderTypeRelLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceDiscountOrderTypeRel service. Represents a row in the &quot;CommerceDiscountOrderTypeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceDiscountOrderTypeRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceDiscountOrderTypeRelImpl
 * @see CommerceDiscountOrderTypeRel
 * @generated
 */
public abstract class CommerceDiscountOrderTypeRelBaseImpl
	extends CommerceDiscountOrderTypeRelModelImpl
	implements CommerceDiscountOrderTypeRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce discount order type rel model instance should use the <code>CommerceDiscountOrderTypeRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceDiscountOrderTypeRelLocalServiceUtil.
				addCommerceDiscountOrderTypeRel(this);
		}
		else {
			CommerceDiscountOrderTypeRelLocalServiceUtil.
				updateCommerceDiscountOrderTypeRel(this);
		}
	}

}
// SB-Hash:874280873