{{- $liferayDefault := index .Values "liferay-default" | default dict -}}
{{- $overlay := $liferayDefault.overlay | default dict -}}
{{- if and $overlay $overlay.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $overlay.bucketName }}
spec:
    accessModes:
        -   ReadWriteMany
    capacity:
        storage: 10Gi
    claimRef:
        name: {{ $overlay.bucketName }}
        namespace: {{ .Release.Namespace }}
    csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeAttributes:
            bucketName: {{ $overlay.bucketName }}
        volumeHandle: {{ $overlay.bucketName }}
    mountOptions:
        -   gid=1000
        -   implicit-dirs
        -   uid=1000
    storageClassName: {{ $overlay.bucketName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $overlay.bucketName }}
spec:
    accessModes:
        -   ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: {{ $overlay.bucketName }}
{{- end }}