defaults:
    run:
        shell: bash
env:
    CHART_VERSION: "0.0.0"
    GAR_REPO: "us-central1-docker.pkg.dev/liferay-artifact-registry/liferay-helm-chart"
jobs:
    publish-cloud-helm-chart:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Calculate Helm chart version
                run: |
                    LATEST_HELM_CHART_TAG=$(git describe --tags --match="helm-chart-*" HEAD)

                    PUBLISH_VERSION=${LATEST_HELM_CHART_TAG#"helm-chart-"}

                    echo "CHART_VERSION=${PUBLISH_VERSION}"
                    echo "CHART_VERSION=${PUBLISH_VERSION}" >> ${GITHUB_ENV}
            -   name: Package Helm chart
                run: |
                    TEMP_DIST_DIR="${{ runner.temp }}/dist"

                    mkdir ${TEMP_DIST_DIR}

                    helm package --destination ${TEMP_DIST_DIR} --version ${CHART_VERSION} .
                working-directory: ./cloud/helm
            -   name: Log in to registry
                run: echo "${{ secrets.GAR_KEY }}" | helm registry login ${GAR_REPO} --password-stdin --username _json_key_base64
            -   name: Push Helm chart to registry
                run: |
                    OCI_URL=$(echo "oci://${GAR_REPO}" | tr '[:upper:]' '[:lower:]')

                    for file_name in *.tgz
                    do
                            echo "${file_name}"

                            helm push "${file_name}" "${OCI_URL}"
                    done
                working-directory: ${{ runner.temp }}/dist
on:
    push:
        branches:
            - master
        paths:
            - cloud/**