defaults:
    run:
        shell: bash
jobs:
    test-cloud-helm-chart:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Install latest version of Kind
                run: |
                    curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64

                    chmod +x ./kind

                    sudo mv ./kind /usr/local/bin/kind
            -   name: Verify Kind installation
                run: kind version
            -   name: Create Kind cluster
                run: kind create cluster
            -   name: Run Helm test
                run: |
                    helm upgrade -i liferay --wait .

                    helm test liferay
                working-directory: ./cloud/helm
on:
    push:
        branches:
            -   master
        paths:
            -   cloud/**