/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat740.model.impl;

import com.liferay.portal.tools.service.builder.test.compat740.model.ArrayableEntry;
import com.liferay.portal.tools.service.builder.test.compat740.service.ArrayableEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ArrayableEntry service. Represents a row in the &quot;ArrayableEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArrayableEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArrayableEntryImpl
 * @see ArrayableEntry
 * @generated
 */
public abstract class ArrayableEntryBaseImpl
	extends ArrayableEntryModelImpl implements ArrayableEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a arrayable entry model instance should use the <code>ArrayableEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ArrayableEntryLocalServiceUtil.addArrayableEntry(this);
		}
		else {
			ArrayableEntryLocalServiceUtil.updateArrayableEntry(this);
		}
	}

}
// SB-Hash:857317598